### ISSUE TITLE
Object must have more than one UV map and texture (world scale UV)

### ISSUE THREAD

**Issue by tuomammela** [nutti/Magic-UV#100]
Why do I get this error message? I'm trying to measure and apply world scale uv. It works for one object and not for another. Adding "more than one" UV map doesn't help. And it works for object that doesn't have "more than one" textures. Why would this operation need two UV's and textures in the first place?

Is this a bug or some mysterious feature that is not explained in the docs?

Attached is an example cube to which I can't apply world scale uv measure.

[More than one uv.zip](https://github.com/nutti/Magic-UV/files/2292776/More.than.one.uv.zip)

**Comment by nutti** [comment]
@tuomammela 

Hi,
Thanks for your bug report.

> Why do I get this error message?

At first, I will show you the requirements of World Scale UV.
The objects measured/applied must have more than **UV map** and **Texture**.
This is needed because World Scale UV calculates texel density from texture size and UV coordinates.

> Is this a bug or some mysterious feature that is not explained in the docs?

Thanks for sharing the file. I checked your .blend file.
However, I could not find the reason for this problem.
Is there any special operations before making the .blend file?

**Comment by tuomammela** [comment]
> objects measured/applied must have more than UV map and Texture

Please use accurate words, I have trouble understanding you. Object must have _at least_ 1 UV map and texture, **or** _more than_ 1? Is it enough to have texture in the uv image editor window, or does it need to be in the material?

> Is there any special operations before making the .blend file?

1. Add a cube
2. Add seams to cube
3. Unwrap cube
4. Create image in uv image window
5. Try to apply world scale

I don't think any of those are special operations.

**Comment by nutti** [comment]
> Object must have at least 1 UV map and texture, or more than 1? Is it enough to have texture in the uv image editor window, or does it need to be in the material?

The requirement is as follows. Does this clear your problem?

* Assign 1 or more than 1 (at least 1) UV map to the mesh
* Assign texture to the each UV map (I think this equals to assigning texture to the material)
* Edit mode

>  I don't think any of those are special operations.

Thanks, I got it.

**Comment by tuomammela** [comment]
> I think this equals to assigning texture to the material

Okay this seems so far to solve the issue. Is it possible to make this operation work without texture assigned to material? So that I could input a texture size, for example 1024, and the operation would then assume that UV space 0-1 is 1024 pixels.

If there are many textures in the material, and they are different size, which of them would currently be used for calculations? I think manual input would be much more useful and not ambiguous.

**Comment by nutti** [comment]
Thanks for your feedback.
I will consider your suggestion, and make a prototype about it.
Can you review new interface after I implement it?

**Comment by tuomammela** [comment]
Awesome! Yes of course I can try it, just leave a message when you're ready.

**Comment by nutti** [comment]
@tuomammela 

I added the mode option **User (Texture Size)**.
I hope this option meats your requirements.

https://github.com/nutti/Magic-UV/archive/issue_100.zip

![magic_uv_issue100](https://user-images.githubusercontent.com/1463952/44523271-3ed2ff80-a714-11e8-92fd-0bd5db4f4501.png)

If there is no problem, I will merge this patch to develop branch.

**Comment by tuomammela** [comment]
Okay texture size input is great. But where is the density input? How can you calculate UV-island size if you don't know what density I'm looking for?

Now it just scales to 0.

**Comment by nutti** [comment]
Sorry, I have a question.  
Why density is needed as input? Density is calculated by the **Measure** button.  
I'm not sure the user's workflow very much, so please give me an idea about this.

**Comment by tuomammela** [comment]
First off, measure doesn't work. It throws the "Object must have more than one UV map and texture "-error.

Secondly, I want to directly specify density, so that I can easily set multiple objects to have same pixel density (if using same texture size).

So:
- Hey cube, you have been unwrapped, and I'm going to use 2k brick texture on you. Scale the uv's so that you have 100 pixels per meter.
- Hey you monkey head, you need to use the same 2k brick texture, I need to have 100 pixels per meter so that your bricks are also correctly sized and consistent relative to Mr Cube.

So, why prevent me from manually inputting the density?

**Comment by nutti** [comment]
> I want to directly specify density, so that I can easily set multiple objects to have same pixel density (if using same texture size)

Thank you very much!  
I understand why density needs to be input by user from your comment.  
I will tackle another prototype. Can you review again after I implemented?

**Comment by tuomammela** [comment]
Now it seems to work and makes sense. This will be a nice addition to your addon for sure.

Though you should fix measurement to work with user values, now it just throws error. Measurement of course uses only the texture size values.

**Comment by nutti** [comment]
@tuomammela 

thanks.

> Though you should fix measurement to work with user values, now it just throws error

I think UI should be changed by the **Mode** option.
So, I will change UI as below.

* **User:** only shows the density
  * I think this option shares the Texture size between source and destination. Is my understanding right?
* **Scaling:** only shows the density (same as now)
  * I will change the mode name as **Scaling density**.
* **Constant:** only shows the density (same as now)
  * I will change the mode name as **Same density**.
* **Proportional:** shows all information
  * I will change the mode name as **Proportional to Mesh**

What do you think of this idea?

**Comment by tuomammela** [comment]
Well I only need full manual mode, so I have no opinion about the others. I think clear name for manual mode is manual. :)

How do you deal with materials that have multiple, different sizes of textures? If I calculate density for material that has 1k 2k and 4k textures, which one do you use for calculation (when not using user specified texture size)?

**Comment by nutti** [comment]
> Well I only need full manual mode, so I have no opinion about the others. I think clear name for manual mode is manual. :)

> How do you deal with materials that have multiple, different sizes of textures?

**Measure** operation is already able to deal with this situation.
But **Apply** operation is only to take consider only 1 texture.

**Comment by nutti** [comment]
Sorry for updating.

I fixed this issue and commited to develop branch.
