### ISSUE TITLE
UV sculpt looks interface

### ISSUE THREAD

**Issue by crantisz** [nutti/Magic-UV#101]
After enabling UV sculpt can't do anything in tools panel, including stop sculpting, change brush or something else. 

![peek 2018-08-28 10-02](https://user-images.githubusercontent.com/1749968/44706372-07fd4080-aaaa-11e8-8760-9468092b7422.gif)

The only one way to exit sculpting - goto object mode, and click in viewport. (Or re-enable add-on)

**Comment by nutti** [comment]
Hi,

I think this has already fixed.
Can you check the develop version?

https://github.com/nutti/Magic-UV/archive/develop.zip

**Comment by nutti** [comment]
@crantisz 

Any update?
If there is no response, I will close issue in this weekend.

**Comment by nutti** [comment]
> Absolutely no difference. But I found why it doesn't work for me. I use Region Overlap, and you probably not.

Thanks.
I can reproduce your issue.

> But even if region overlap is turned off - viewport is buggy, for example, tooltips overlaps the interface, viewport can't be rotated or moved

I can not get this issue.
After turning off the Region Overlap, it also works correctly in my environment.

**Comment by nutti** [comment]
And I would like to ask you if it doesn't work UV Bounding Box as well when you turn on Region Overlap.

**Comment by crantisz** [comment]
Looks like the same issue
![peek 2018-09-13 14-10](https://user-images.githubusercontent.com/1749968/45485032-d4cfd800-b75e-11e8-9856-a0d592c2c4c7.gif)

**Comment by nutti** [comment]
@crantisz 

Thanks, I fixed this issue now.
It's in develop branch.

https://github.com/nutti/Magic-UV/archive/develop.zip

can you check develop version?

https://github.com/nutti/Magic-UV/wiki/Installation

**Comment by crantisz** [comment]
Looks like that it works better now. About tooltip:

![peek 2018-09-21 16-45](https://user-images.githubusercontent.com/1749968/45884957-dc762900-bdbd-11e8-9286-bf481c58ec53.gif)

here how to reproduce:

1. hover mouse cursor on button (you can wait until tooltip will show, or left button earlier)
2. move at 3D view and hold mouse a bit

**Comment by nutti** [comment]
@crantisz 

> If viewport are not looked, you can move and rotate it, isn't it good?

I fixed this issue.

> But even if region overlap is turned off - viewport is buggy, for example, tooltips overlaps the interface, viewport can't be rotated or moved

I could this issue because this is the limitation of blender itself.
But I think this is not big problem, so I will remain this issue for now.

If you have any problem, please reopen or create new issue. Thanks for your cooperation.
