### ISSUE TITLE
[REQ]Idea for better changelog updating

### ISSUE THREAD

**Issue by schroef** [nutti/Magic-UV#102]
I was looking at a changelog tonight and noticed some great example of much easier update system, or atleast to maintain much easier.

I noticed that this addon also uses that markup table version which is really a pain in the butt to update it properly.

Have a look at this link, https://keepachangelog.com

Just look at the example how the [changelog.md ](https://github.com/olivierlacan/keep-a-changelog/blob/master/CHANGELOG.md) Its much easier to update. Though i like how the tabel looks editing it is super weird and sloppy all the time, especially when you want use bullet lists in the last column. This method is much easier.

Their github page is bit weird though as i dont really understand that part. I think its more of a method to make this in all kinds of languages. Not very clear.

Main thing was i like how it looks and especially how much easier it is to update and edit the changelog file

**Comment by nutti** [comment]
@schroef 

nice catch!
I added CHANGELOG.md and move changelog to it.
can you review this?

https://github.com/nutti/Magic-UV/tree/issue_102

**Comment by nutti** [comment]
This patch is now in develop branch.

Thanks for your idea.

**Comment by nutti** [comment]
Sure, I will merge it later.

**Comment by schroef** [comment]
Great, its so easy to read this kind of setup
