### ISSUE TITLE
Add-on activates only after reopenning Blender

### ISSUE THREAD

**Issue by henriquebg88** [nutti/Magic-UV#103]
I activated the addon and not all features were Available. The ones on the properties panels wasn't showing up. Only the options when hitting U for unwraping. 
After closing e reopening Blender, it was appearing on the panels where it should. 
i am using Blender 2.79a and the built-in version of the addon

**Comment by nutti** [comment]
Can you check #86 ?
I did not commit newest version to Blender repository.

But I think it's a time to update Blender repository as Magic UV v5.2.
For now, can you use develop version?

https://github.com/nutti/Magic-UV/archive/develop.zip

**Comment by nutti** [comment]
Please delete v4.4 at first.
https://github.com/nutti/Magic-UV/wiki/Installation

> Notice: If you use Blender which version is >= 2.79, you must remove released Magic UV add-on at first.

I think you may not follow this instruction.

**Comment by nutti** [comment]
@henriquebg88 

Any update on this issue?
I will close this issue if you have no problem in this weekend.

**Comment by henriquebg88** [comment]
I didn't try. I am so busy on my job that I forgot about it. But you can close it.
I gave up using the add-on because I had too mad crashes. Probably because of out dated version

**Comment by nutti** [comment]
OK, I understood.
I will upload newest version after I resolve all issues on milestone.
Please check after when this add-on is included on Blender itself.

Thanks for your report.
