### ISSUE TITLE
More than 2uv's must be selected

### ISSUE THREAD

**Issue by radeonoff** [nutti/Magic-UV#104]
whatewer i do, im' getting this error
![2018-12-06 1](https://user-images.githubusercontent.com/43900710/49587139-83f60700-f97c-11e8-91cf-8558f6bab8ce.png)

**Comment by nutti** [comment]
How did you select UVs?
I think this error is raised from your wrong operation.

**Comment by radeonoff** [comment]
i dont get it. what is "select uv" even mean? uv chanels or what?
 now it sayng "all uv's are not separated"
![2018-12-07](https://user-images.githubusercontent.com/43900710/49631350-1349fb80-fa0b-11e8-9fa7-7e151414dd10.png)

**Comment by radeonoff** [comment]
now i disabled synchronyzing uv and get shitload of errors
![2018-12-07 1](https://user-images.githubusercontent.com/43900710/49632367-e4358900-fa0e-11e8-894d-d08332fee7be.png)
![2018-12-07 2](https://user-images.githubusercontent.com/43900710/49632368-e4358900-fa0e-11e8-80bd-1f3933d4d566.png)

**Comment by nutti** [comment]
Maybe your problem comes from the UV selection.
If you use **Smooth UV** and **align UV**, you must select the most outer edge.

**Comment by nutti** [comment]
@radeonoff 

Hi,

If you can't make sense about the usage of **Smooth UV** and **Align UV**.
You can refer below tutorial video.
These features are ported from imdjs's UV_Tool.

https://github.com/nutti/Magic-UV/issues/97

**Comment by nutti** [comment]
There is no response about this, so I close this issue for now.

**Comment by benben962** [comment]
Hi there,

I also systematically have this error no matter the project I select. Even if I try with a basic cube with the basic unwrapping in Blender, I get the same error when I try to use "Align UV".

I stay at your disposal for any further information you would need, all best,
Ben

**Comment by nutti** [comment]
@benben962 

Great!
I could not get this error for my environment.
Any information is welcomed. Thanks!

**Comment by Andrew52d** [comment]
Hi Nutti

I just started using your Addon today.  I found it after trying to find an easy way of aligning edges and came across your Addon built into Blender

Just as the others, I'm getting the same issue when trying to Align edges on any asset
`More than 2 UVs must be selected`
At first I thought it was something to do with my mirror modifiers so I disabled them, got the same result.  I then tried turning off UV sync and performing the same operation.  There I got a new error 

`Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\magic_uv\op\align_uv.py", line 597, in execute
    loop_seqs, error = common.get_loop_sequences(bm, uv_layer)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\magic_uv\common.py", line 786, in get_loop_sequences
    isl_info, closed)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\magic_uv\common.py", line 733, in __get_loop_sequence_internal
    nplp = __get_next_poly_loop_pair(nlp)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\magic_uv\common.py", line 689, in __get_next_poly_loop_pair
    v2 = pair[1].vert
IndexError: list index out of range

location: <unknown location>:-1

`

![image](https://user-images.githubusercontent.com/62970754/78086652-9e7f9b00-738c-11ea-8282-bd1093eb3a71.png)
This being the object i'm trying to run the operation on. 

I'm running Blender 2.82.7
Magic UV 6.2.0

(Apologies if the formatting is messed up, first time posting on Github)

**Comment by nutti** [comment]
@Andrew52d 

Thanks for reproducing the error.
If you don't mind, could you give me reproducible file?
This information helps me a lot.

**Comment by Andrew52d** [comment]
> @Andrew52d
> 
> Thanks for reproducing the error.
> If you don't mind, could you give me reproducible file?
> This information helps me a lot.

Sure thing!  I'll Email you the file through your posted address at nutti.metro@gmail.com
I stripped everything out except that piece, can confirm it still errors out

**Comment by R-J-Dawson** [comment]
Hi there,

Was this issue ever addressed with Magic-UV? I've been having the same problem myself, no matter what I do (enable/disable sync selection, only edit the UVs of one object/multiple objects, etc), I always get the error "More than 2 UVs must be selected".

Could this be a confliction with another addon?

Kind regards,
-R

**Comment by andrelevi** [comment]
Hello, I'm running into this same issue on Blender 2.83.4, not using any other sort of add-on that might be conflicting. Anyone find a solution?

**Comment by skarkkai** [comment]
Getting this error 2.92.0 for no reason that I can tell.

**Comment by MattFagan** [comment]
This is a broken add-on. It should be deleted. Since the author no longer monitors its massive broken state in Blender 3.0.

**Comment by nutti** [comment]
@MattFagan 

We're currently rewriting whole codes for **Smooth UV** and **Align UV** because these features does not work in specific case.
Sorry for delaying the support (because of my personal reason)...
If there is an another error, it is helpful for us.

**Comment by 01levent01** [comment]
> UV'leri nasıl seçtiniz? Bu hatanın yanlış işleminizden kaynaklandığını düşünüyorum.

I see the problem.
You are trying to edit with You have 2 or more objects.
select only 1 object and enter the UV editor.

**Comment by 01levent01** [comment]
I see the problem.
You are trying to edit with You have 2 or more **objects.**
select only **1 object** and go to UV editor.
