### ISSUE TITLE
It can't activate the add-on on macOS 10.13.6 & Blender 2.80 2019-01-13

### ISSUE THREAD

**Issue by Oxervision** [nutti/Magic-UV#105]
Hi, when I try to activate the add-on in Preferences window it appear this message:
Traceback (most recent call last):
  ```
File "/Applications/Blender/BLENDER 2.80/blender.app/Contents/Resources/2.80/scripts/modules/addon_utils.py", line 393, in enable
    mod.register()
  File "/Applications/Blender/BLENDER 2.80/blender.app/Contents/Resources/2.80/scripts/addons/uv_magic_uv/__init__.py", line 111, in register
    if bpy.context.user_preferences.addons['uv_magic_uv'].preferences.enable_builtin_menu:
AttributeError: '_RestrictContext' object has no attribute 'user_preferences'
```

**Comment by nutti** [comment]
Thanks for sharing your problem.
This error comes from the API changes of Blender.
I'm now tackling not to show this error. Would you wait until I fix this one?

**Comment by schroef** [comment]
@nutti 
I think i pointed out in a thread on blenderartist. But "user_preferences" had been changed and is called "preferences" now. Its an easy fixed, i got the addon now loading without errors.

**Comment by Oxervision** [comment]
Hi Roumbout, good see you here, for me the addon doesn’t load, when I try to actívate it in Preferences it appears the previous message, I can see it in the Tools bar and I can use it in that session but when I close Blender and I reopen it the addon is deactivated in Preferences window.
Regards,
Oxer

**Comment by schroef** [comment]
@Oxervision,

When you activate an addon you need to save preferences. Otherwise they will not be saved and thus addon is NOT activated the next time you start Blender. I dont think the issue is related to the addon be not active.

**Comment by schroef** [comment]
@Oxervision 

ps also change line 121
<img width="853" alt="screen shot 2019-01-13 at 23 14 39" src="https://user-images.githubusercontent.com/6923008/51095162-07c7be00-1789-11e9-9f65-4664391cd49a.png">

**Comment by schroef** [comment]
There are actually more instance of user_preferences. These need to be changed as well

https://github.com/nutti/Magic-UV/search?q=user_preferences&unscoped_q=user_preferences

**Comment by Oxervision** [comment]
> 
> When you activate an addon you need to save preferences. Otherwise they will not be saved and thus addon is NOT activated the next time you start Blender. I dont think the issue is related to the addon be not active.

I know it, but the problem was that the Magic UV stayed unmarked after click on checkbox.
I have changed the rest of user_preferences in all files that you have said me.

**Comment by schroef** [comment]
I had not seen an error from the other scripts. Mainly the init file. Ill check if it works now.

**Comment by schroef** [comment]
I dont see any errors in the dev version.

But still dont get why the addon state 6.0.0
<img width="497" alt="screen shot 2019-01-15 at 19 38 48" src="https://user-images.githubusercontent.com/6923008/51217110-39619600-18fd-11e9-87a6-5a51c1d82686.png">

**Comment by nutti** [comment]
@schroef 

Thanks for checking.
I will release Magic v6.0 in a few weeks.

**Comment by schroef** [comment]
Ah okay, so that is the 2.8 Milestone i guess
