### ISSUE TITLE
magic UV does not activate

### ISSUE THREAD

**Issue by virgoss** [nutti/Magic-UV#106]
**System Information**
  
* OS: Ubuntu 18.04
* Blender version: 2.80 beta
* Add-on version: 6.0

**Expected behavior**  
Enabling add-on

**Description about the bug**  
When i try to enable the add-on, stop it with errors.

Screen shot attached.
![schermata da 2019-01-26 22-28-17](https://user-images.githubusercontent.com/5464370/51792970-bde3cc80-21b9-11e9-9c05-b8d4fce81f4a.png)

**Comment by nutti** [comment]
I think this error raised from the version of Magic UV is old.
I downloaded and checked the newest Blender today, but there is not newest version for now.
I think the newest Magic UV will be included to Blender itself in future. But I'm not sure about when it is.

Could you wait until the Blender includes the newest version, or install manually?
https://github.com/nutti/Magic-UV/wiki/Installation

**Comment by nutti** [comment]
Now, Magic UV is in Blender itself.
And I confirmed that there is no issues about this version.
So, I close this.
