### ISSUE TITLE
MagicUV traceback call error, unable to activate the addon

### ISSUE THREAD

**Issue by Mak7free** [nutti/Magic-UV#108]
**System Information**
  
* OS: [Windows 10 x64]
* Blender version: [2.80 built 20/02/2019]
* Add-on version: [6.0.0]
![a1faf796-47fd-44cc-a32d-9064898aa6aa png](https://user-images.githubusercontent.com/48034484/53451185-3a313000-3a44-11e9-84fb-2323ee813b3e.jpg)

**Expected behavior**  
*The behavior you expect about the feature you reported.*

**Description about the bug**  
*The description about the bug.*

**Screenshots/Files** [Optional]  
*It is good to solve the bug if you attach the screenshots or .blend file.*

**Additional comments** [Optional]

**Comment by Giorat** [comment]
Did you try to install this addon from the zip file?

**Comment by nutti** [comment]
Could you tell me the add-ons you enabled.
I think this problem is related to the other add-ons.

**Comment by Mak7free** [comment]
@Giorat yes sir. that's how i tried. i did try looking for the python script but got scared when i couldn't find the one that looked like the main one.
@nutti  well i enabled all the addons that are available by default in blender during the first install. i however did not add any addons from the community. i did add makehuman and related addons.

**Comment by nutti** [comment]
@Mak7free 

Hi, I'm very sorry for late response.
I checked the newest version of Blender 2.8 (Hash: bfef3bce1a93, Date: 2019-05-07 00:16), but no error is raised in my environment.
Could you check again with newest Blender?

**Comment by nutti** [comment]
Magic UV v6.1 is released now.
Maybe this problem is already fixed.
If you have any problem, please make new issue or reopen this issue.
