### ISSUE TITLE
New Feature: Random Island Colour (RCS Suggestion)

### ISSUE THREAD

**Issue by Ammusionist** [nutti/Magic-UV#110]
**Pre-Paint UV Image with random colours according to Island Layout**  
Taken from the following Right-Click-Select suggestion:
[Random UV color](https://blender.community/c/rightclickselect/Vddbbc/)
The idea is after laying out the UV Islands, a random colour is applied to each island to better co-relate the 2D UV Image and 3D Mesh.

I thought that this suggestion would be best served from within a plug-in rather than Blender core and wanted to mention it here for your consideration.

**Are you willing to contribute about this feature. (Yes/No)** 
I apologise, but I'm not so well versed in Python.

**Screenshots** [Optional]  
*Screenshots are in RCS suggestion.*

**Additional comments** [Optional]
Issues to consider 
* Overlapping islands
* Altering UV after painting (Auto repaint?)

**Comment by nutti** [comment]
@Ammusionist 

Hi,

Thanks for the feature request.
Could you tell me about two features you requested?

> Overlapping islands

Is it same as #80 ?

> Altering UV after painting

I think this feature changes the color of texture because of Blender's specification.
Is it allowable to change the color of texture if this feature is on?

**Comment by nutti** [comment]
@Ammusionist 

This feature is now supported.
You can use this feature from master branch (will be released with v6.3).
Please try this feature from **Image Editor** > **UV Inspection** > **Paint UV Island**.
