### ISSUE TITLE
Unable to activate MagicUV

### ISSUE THREAD

**Issue by BlumpkinKing87** [nutti/Magic-UV#111]
**System Information**
  
* OS: [Windows 10]
* Blender version: [2.8]
* Add-on version: [6.0.0]

**Expected behavior**  
To be able to activate MagicUV

**Description about the bug**  
I'm unable to activate MagicUV

**Screenshots/Files**
![image](https://user-images.githubusercontent.com/50567298/57598017-2f504c80-7517-11e9-933a-69ead92fee37.png)

**Comment by nutti** [comment]
@BlumpkinKing87 

Hi,

Could you tell me about your environment to reproduce your error?
At least, I need below information.

* Blender version. Blender 2.8 is not released yet and develop rapidly, so I need to build date or hash ID.
* Are you using the built-in Magic UV?
* Is there any add-ons you are enabled?

This error is often reported recently.
From my recent investigation, there is no error about recent Blender version.

**Comment by srlake31470** [comment]
I'm also having issues trying to install.
I got an error when I installed magic uv file magic_uv.zip.
It shows up in the addons finally,(magic uv 6.0 zip) didn't install at all.
However I'm getting errors.

**Comment by nutti** [comment]
@srlake31470 

Did you delete the built-in Magic UV add-on before installing Magic UV?
And, I would like to know the detailed information as I shown in above.

**Comment by nutti** [comment]
Magic UV v6.1 is released now.
Maybe this problem is already fixed.
If you have any problem, please make new issue or reopen this issue.
