### ISSUE TITLE
UVTransfer is Broken

### ISSUE THREAD

**Issue by mifth** [nutti/Magic-UV#116]
* OS: [e.g. Windows]
Blender 2.81
Magic UV 6.2

Hello! It looks like UV Transfer is broken. I tried to paste uvs but it writes "2 Faces must be selected". 

![image](https://user-images.githubusercontent.com/2251298/67396460-4e680580-f5b0-11e9-8aee-52538b7ea4e0.png)

**Comment by mifth** [comment]
[tmp.zip](https://github.com/nutti/Magic-UV/files/3762541/tmp.zip)

Here is my example test.

**Comment by nutti** [comment]
@mifth 

Thanks for your report. Nice catch!
I will fix it, but I can not spend my time about this recently.
Could you wait until my busy days is gone?

If you have time, it's pleasure that you send me Pull Request :-)
Source code of Transfer UV is https://github.com/nutti/Magic-UV/blob/master/src/magic_uv/op/transfer_uv.py .
Thanks again!!

**Comment by mifth** [comment]
Hi.
I deleted pycache files of the Magic UV and now all works fine. Strange that it happened.
TYhanks, I close the issue.

**Comment by nutti** [comment]
Understood. Thanks for the investigation.
