### ISSUE TITLE
World Scale UV  not applying to all UV islands

### ISSUE THREAD

**Issue by omarM1993** [nutti/Magic-UV#123]
**System Information**
  
* OS: [e.g. Windows]
* Blender version: [ 2.82]
* Add-on version: [ 6.2]

Make a cube, mark all edges as seams and uv unwrap it, in the uv editor resize uv islands randomly (make some big others small) , now  select all faces and  apply World Scale UV  on manual mode (eg 1024 200 desity)
**Expected behavior**  
each face (UV island) get similar size with the expected density

*The behavior  I got*
the whole uv map get scaled strangely ,   if I want all faces to  get  similar size with the expected density I have to select them one by one  and apply World Scale UV,  which is  inconvenient if I have a uv map with many uv islands

**Comment by nutti** [comment]
@omarM1993 

Sorry for late reply.
Thanks for sharing your issue!

Current **World Scale UV** decides the target size using the whole mesh size.
So, your request indicates to use the face size (or UV island size),doesn't it?

**Comment by nutti** [comment]
This feature is now merged to master branch.
You can specify **Area Calculation Method** to specify how to calculate area.
For this issue's request, specify **UV Island** or **Face**.

<img width="271" alt="github_20200607" src="https://user-images.githubusercontent.com/1463952/83965411-98f38380-a8ee-11ea-8979-49600f0dcf98.png">

**Comment by omarM1993** [comment]
thank you you saved my day!!!!!
