### ISSUE TITLE
Improve performance of 3dview UI moving

### ISSUE THREAD

**Issue by Fak3** [nutti/Magic-UV#126]
I have a DAZ-3D human model with 15k vetrices, and when I am trying to move uv in the 3d viewport, it eats 100% cpu and takes about 5 seconds to finish the stroke and update the visible result.

**Comment by nutti** [comment]
@Fak3 

Thanks for your suggestion!
I optimized Move UV feature.
Before this patch is merged to master branch, could you try prototype version?
https://github.com/nutti/Magic-UV/archive/spike_126.zip

**Comment by nutti** [comment]
@Fak3 

Thanks for your testing!
I will merge this patch ASAP.

**Comment by nutti** [comment]
The patch is already merged to master branch.
