### ISSUE TITLE
UV sculpt AttributeError: Vector subtraction: (NoneType - Vector) invalid type for this operation

### ISSUE THREAD

**Issue by Fak3** [nutti/Magic-UV#127]
**System Information**
  
* OS: LInux
* Blender version: 2.83
* Add-on version: Git master

When i tried to sculpt UV in 3d view edit mode, it fails with error: 
```
Traceback (most recent call last):
  File "/home/z/soft/blender-2.83-e8dd8c2829f3-linux64/2.83/scripts/addons/magic_uv/op/uv_sculpt.py", line 460, in modal
    self.__stroke_init(context, event)
  File "/home/z/soft/blender-2.83-e8dd8c2829f3-linux64/2.83/scripts/addons/magic_uv/op/uv_sculpt.py", line 269, in __stroke_init
    diff = loc_2d - self.__initial_mco
AttributeError: Vector subtraction: (NoneType - Vector) invalid type for this operation

location: <unknown location>:-1
```

**Comment by nutti** [comment]
@Fak3 

I could not reproduce this error.
Could you give me your detail situation?
I think this error comes from the model location.
Thanks.

**Comment by Fak3** [comment]
Here is the blend file: https://drive.google.com/file/d/1U2MhaL0f6Ry6SB4c0YYDyIG00xbzk9qf/view?usp=sharing
How to reproduce (see screenshot):

* Open the UV editing workspace
* Select all faces
* Enable UV sculpt in N-menu
* Try to sculpt with it over the mesh

![Screenshot_20200531_131601](https://user-images.githubusercontent.com/991641/83349881-b2ba2700-a340-11ea-9480-c8550070f609.jpeg)

**Comment by nutti** [comment]
@Fak3 

I could reproduce this issue.
Thanks to your cooperate, I could fix this issue (It is already in master branch).
