### ISSUE TITLE
UV unwraping for multiple object

### ISSUE THREAD

**Issue by koukwst** [nutti/Magic-UV#132]
UV unwrapping support for multiple object selection. I.e. Select some objects and unwrap them together. Since Blender 2.8 users are used to edit multiple objects and unwrap them all at once. This feature will help multiple user who prefer Magic UV, since it is more improved compared to the default methods.

**Comment by nutti** [comment]
@koukwst 

Sorry, I misunderstood your request.
I think your request is UVW Mapping, so I will tackle this first.

**Comment by nutti** [comment]
Now this feature is merged into master branch.
