### ISSUE TITLE
Stacking/Packing multiple identical/similar mesh uv islands on a same object

### ISSUE THREAD

**Issue by 20209726** [nutti/Magic-UV#134]
**System Information**
  
* OS: [ Windows 7]
* Blender version: [2.83]
* Add-on version: [6.2]

Hi nutti, thank you for the great add-on!  I found some issue while working on packing uv islands. I don't know if this is a bug or should be a new feature.  Pardon me if this have been discussed.  :)

**Expected behavior**  
Objective: stacking multiple identical/similar mesh uv islands on a same object.

**Description about the bug**  
1. Tried with PACK UV, but seems not doing anything with different islands on a same object. But works with different objects with same mesh. (ex: marked seams for all edges of a cube, made 6 island squares, not stacking when PACK UV)

2.Tried again with MIRROR UV, some times works with symmetric mesh on global axis. But only in global axis. Hope it can do with local/normal axis as well. (ex: some parts of a mechanic model, could be locally symmetrical)

3.Tried again with COPY/PASTE UV. This have protential, but not working correctly. 
And also found a BUG?:  When selecting source face, if I use box select, it gives NO FACE SELECTED warning. If I selected a face, and select linked by material/seams, it shows only selected 1 face.  Seems the selecting only recorded the mouse clicking selection of faces one by one. This could be a lot of work while working with a big mesh.

My solution to my Objective: unwrap the uv of the source mesh > duplicate and seperate it > mirror then join and replace the target mesh.   But this only works well with object like symmetrical character with not too many similar parts.

If I need to work with an object with 30+ similar parts, and each part could use have multiple repeating mesh. This would have a lot of repeating work.  While it could be a lot faster with auto stacking similar mesh on one object. :)

Thank you very much! 

**Screenshots/Files** [Optional]  
*It is good to solve the bug if you attach the screenshots or .blend file.*

**Additional comments** [Optional]

**Comment by nutti** [comment]
@20209726 

Sorry for very late reply. I have been working on other project.
And thanks for your feedback with deep inspection.

At first, I try to check first one.

> Tried with PACK UV, but seems not doing anything with different islands on a same object. But works with different objects with same mesh.

I'm curious this behavior,
Multiple objects editing mode is not supported now (I'm just tackling to support this).
Could you explain more detail about it.

**Comment by 20209726** [comment]
Hi nutti,  thank you for checking back on the issue!   
I haven't been getting in the same task lately. But as I remember, the first one is like described in the post: (ex: marked seams for all edges of a cube, made 6 island squares, not stacking when PACK UV)
Meaning when I tried to Pack UV of a cube, I want to stack all 6 face UVs of the cube.  So I marked seams for all 12 edges of the cube, then all faces' UV become seperate square islands. Then I PACK UV, but these squares are not stacking.

**Comment by nutti** [comment]
@20209726 

Thanks for your explanation.
I recently try to improve Pack UV, and I found that same but separated island will not be overlapped.
So, I start to try adding a new option which realizes your intention.
If you still use this add-on, I would like to receive your feedback.

**Comment by 20209726** [comment]
That's great!  Appreciate!  I will definitely let you know if I use it again.

**Comment by nutti** [comment]
> 1. Tried with PACK UV, but seems not doing anything with different islands on a same object. But works with different objects with same mesh. (ex: marked seams for all edges of a cube, made 6 island squares, not stacking when PACK UV)

This issue is now fixed by expanding the configurable ranges of the options **Allowable Center Deviation** and **Allowable Size Deviation**.
I think setting a large value (e.g. 10.0) on **Allowable Center Deviation** enables you to merge separated islands.
In addition, you can merge size different islands if you set a large value to the option *Allowable Size Deviation*.

**Comment by nutti** [comment]
> 3. Tried again with COPY/PASTE UV. This have protential, but not working correctly.
And also found a BUG?: When selecting source face, if I use box select, it gives NO FACE SELECTED warning. If I selected a face, and select linked by material/seams, it shows only selected 1 face. Seems the selecting only recorded the mouse clicking selection of faces one by one. This could be a lot of work while working with a big mesh.

Yes, this is a specification of Copy/Paste UV feature.
Blender can not record the selection sequence when we select faces with box selection, so the limitation comes from this.

If you want to copy/paste UV with many faces, you should try to use **Transfer UV** feature instead.

**Comment by nutti** [comment]
@20209726 

> Hope it can do with local/normal axis as well.

I think we should not support normal axis in this feature.
After my investigation, the calculation of normal transform orientation may depend on the internal logic of Blender.
So, we can easily break the feature in future Blender version.

**Comment by nutti** [comment]
The main issue seems that the mirror UV does not work correctly when the transform orientation is global/world.

**Comment by nutti** [comment]
Added 'Origin' option to Mirror UV.

All issues are now fixed. So, I'll close this issue.

**Comment by 20209726** [comment]
Thank you soo much for fixing this!  I can't wait to try it with next project!
Appreciated for all the good work!
