### ISSUE TITLE
Preserve UV dont work in 2.83 

### ISSUE THREAD

**Issue by MrPositivity** [nutti/Magic-UV#136]
**System Information**
  
Windows
2.83.4
6.2.0 

**Expected behavior**  
I assumed that preserver UV should adjust the UV island scale to not be impacted by texture scale, by adjusting aspect ration 
I use texture 2048x4096 and was trying to adjust my UV islands to not be affected by this textures aspect ration 

**Description about the bug**  
when pressing Preserve UV nothing happens.

**Comment by nutti** [comment]
@MrPositivity 

Sorry for the late response.
I think you misunderstood the effect of **Preserve UV Aspect**.

**Preserve UV Aspect** changes the UV ratio without changing the appearance of mesh in View3D.
This is a main purpose of this feature.
If you don't want to change UV ratio, you should change the image directly.

I will close this issue for now.
If you have any questions/issues about **Preserve UV Aspect** feature, please reopen this issue.

**Comment by schroef** [comment]
Im running 2.83 on old OSX computer. usiong v 6.2.0
The operator tries to find images from the file common.py But i dont get why it causes the error "Find more than 2 images
" the if statement makes no sense to me. Because it says this ```f len(images) >= 2:
    #     raise RuntimeError("Find more than 2 images")``` 
    Which means the opposite of the error?!
    If i turn the if statememt of, the operator keep aspect ratio works perferct. Downside is, if i then update my texture using reload, it losses its aspect again
