### ISSUE TITLE
call operator from Python Scripts

### ISSUE THREAD

**Issue by MatthiasThDs** [nutti/Magic-UV#137]
Hi,

I really love your addon. I use it for a long time :) In fact I am writing Python scripts for my company to speed up the modelling process. Kinda like procedural modelling. Therefore UV Magic and especially bpy.ops.uv.muv_uvw_box_map() would be key to make it all work.

But, it seems that your script is not callable from a Python script? What would it take to enable that feature?

The poll operator seems to disallow it:
```
@classmethod
    def poll(cls, context):
        # we can not get area/space/region from console
        if common.is_console_mode():
            return True
        return _is_valid_context(context)
```

I kinda tried to just return true in the poll, it seems to work, but sometimes i get wrong results :)

**Comment by nutti** [comment]
@MatthiasThDs 

Thanks for your feedback!

I think you didn't satisfy the context to execute this operation.
https://github.com/nutti/Magic-UV/blob/91b575b3dadfd595ef409b777c06b7aef969f5c3/src/magic_uv/op/uvw.py#L43-L59

What is your context you try to execute?

**Comment by MatthiasThDs** [comment]
Hi,
I think my context should be right. Just in the "Layout" workspace in Editmode.
I also have an issue using one of your functions in the console:

![image](https://user-images.githubusercontent.com/50454126/95676011-71be0300-0bbb-11eb-9567-6718a9d67de8.png)

**Comment by nutti** [comment]
OK, I understood the issue.

```python
     # only 'VIEW_3D' space is allowed to execute 
     for space in context.area.spaces: 
         if space.type == 'VIEW_3D': 
             break 
     else: 
         return False 
```

I think current context.area is `CONSOLE`.
Currently, all features of Magic UV must be executed from `VIEW_3D`.
Do you want to execute this feature from other areas?

**Comment by MatthiasThDs** [comment]
Yes. I would like to run the functions in a Python Script, which sadly don't have View_3D as current context.

**Comment by nutti** [comment]
@MatthiasThDs 

I think all things we have to do with is deleting below checks.
Other checks are still needed to prevent from the execution in unexpected condition.

```python
     # only 'VIEW_3D' space is allowed to execute 
     for space in context.area.spaces: 
         if space.type == 'VIEW_3D': 
             break 
     else: 
         return False 
```

What do you think?

**Comment by MatthiasThDs** [comment]
Yes I agree.
That would be nice.

**Comment by nutti** [comment]
@MatthiasThDs 

`bpy.context.screen.areas` looks better to me.

BTW, are you interested in contributing to this project about this?
I think all we have to do is change `context.area.spaces`  to like ` for area in context.screen.areas: for area.spaces:`.
I'm now tackling to other issue before releasing v6.4.
So, I will accept your change if you want.

**Comment by MatthiasThDs** [comment]
@nutti 
Yes, i can try to work my way into this github. Never did before, so give me some days.

**Comment by nutti** [comment]
@MatthiasThDs 

Awesome!
I will wait your work.
If you have any trouble to complete this work, please feel free to tell me.
