### ISSUE TITLE
Select Overlapped UVs Issue

### ISSUE THREAD

**Issue by mifth** [nutti/Magic-UV#141]
**System Information**
  
* OS: Windows
* Blender version: 2.91
* Add-on version: 6.2

**Expected behavior**  
Select ok.

**Description about the bug**  
Hello, I've found an issue in selecting overlapped UVs. Only some polygons were selected.

**Screenshots/Files** [Optional]  
[tmp1.zip](https://github.com/nutti/Magic-UV/files/5524180/tmp1.zip)

![image](https://user-images.githubusercontent.com/2251298/98816590-f52c7780-2439-11eb-9afb-4a2626bad971.png)

**Comment by nutti** [comment]
@mifth 

Thanks for your feedback.
I fixed it by introducing the threshold.

https://github.com/nutti/Magic-UV/archive/issue_141.zip

Could you try this one?
If this problem still exists, you can change **Same Polygon Threshold** option.

![github_20201113](https://user-images.githubusercontent.com/1463952/99059595-2647ac00-25e2-11eb-93bc-044662ece386.png)

**Comment by mifth** [comment]
Hello @nutti !
Strange, I cannot install the addon you linked.
![image](https://user-images.githubusercontent.com/2251298/99067906-8fb4c400-25bc-11eb-9403-6f8ab6f43cbe.png)

**Comment by mifth** [comment]
I have blender 2.90, Windows

**Comment by mifth** [comment]
I tested 6.4.0. Works ok at the same machine.

**Comment by nutti** [comment]
@mifth 

It's strange.
Did you follow the installation process?
I think add-on folder is a bit complicated for non-release zip file.

**Comment by nutti** [comment]
@mifth 

Sorry, the document for **unstable** version is missing there.
I fixed the document now.
Could you try to follow the tutorial of **unstable** version by using [issue_141.zpi](https://github.com/nutti/Magic-UV/archive/issue_141.zip) instead of **unstable** version.

**Comment by mifth** [comment]
@nutty

Alright, I downloaded from [here ](https://github.com/nutti/Magic-UV/tree/issue_141) and installed the addon. It looks like it works ok now. Good job! Thank you a lot. I'm closing the issue.

![image](https://user-images.githubusercontent.com/2251298/99180555-37a2cc80-2738-11eb-889c-b5abcf64ec96.png)

**Comment by nutti** [comment]
@mifth 

Thanks.
I merged fixed patch to master branch.
