### ISSUE TITLE
(UVs) Flip and Overlap Inspection in 3d

### ISSUE THREAD

**Issue by mifth** [nutti/Magic-UV#143]
Hi. 
Is it possible to add Flip and Overlap Inspection in 3d? It would be cool.

![image](https://user-images.githubusercontent.com/2251298/103783740-27c5ab80-504a-11eb-9d9b-f16304e64d03.png)

**Comment by nutti** [comment]
@mifth 

I think it is possible.
Which idea do you want to introduce to the add-on?

* Paint color on the mesh as well as **UV Inspection**
* Select the overlapped/flipped faces as well as **Select UV**

**Comment by mifth** [comment]
It would be super useful! I think color on the mesh as well as UV Inspection would be nice. In this case it would be possible to deselect all and make some changes in 3d while all colors will be seen.

**Comment by nutti** [comment]
OK, I try to add this feature.
But I need a time because I already have other tasks.

**Comment by mifth** [comment]
No worries. Thank you a lot!

**Comment by nutti** [comment]
Sorry for late response.
I will tackle this issue from now.

> Select the overlapped/flipped faces as well as Select UV

At first, I will add the above feature.

**Comment by mifth** [comment]
No worries. Thank you a lot. This feature will be very useful.

**Comment by nutti** [comment]
> Select the overlapped/flipped faces as well as Select UV

This one is now merged into master branch.
The **Selection Method** option and **Sync Mesh Selection** option are added to specify how to select the faces.

I will tackle next one.

> Paint color on the mesh as well as UV Inspection

I think this feature needs to be reviewed before merging into master branch.

**Comment by mifth** [comment]
I have rested. Works nice! You have added a checkbox.

**Comment by nutti** [comment]
@mifth 

> Paint color on the mesh as well as UV Inspection

I have finished to implement this feature.
Could you try it before merging this feature to the master branch?
https://github.com/nutti/Magic-UV/archive/issue_143.zip

I introduced `Display View3D` option to display overlapped/flipped faces in View3D.

**Comment by mifth** [comment]
Hi @nutti 

Awesome! Some things I would check:
- set "Display View3D" True by default.
- I would rename "Display View3D" to "3D"
- I would change polygons transparency to 0.5 just like in UV viewport.
- There is flickering with polygons and red polygons. I tried to play with the code but was not able to change anything as polygons are drawn in 2d.

![image](https://user-images.githubusercontent.com/2251298/107938723-d4bf0c80-6f96-11eb-9043-70cc202550aa.png)

I tried to change to bgl.glVertex3f(co1, co2, co3) but I got exception.

**Comment by mifth** [comment]
[tmp3.zip](https://github.com/nutti/Magic-UV/files/5981150/tmp3.zip)

Here is a model to play with.

**Comment by mifth** [comment]
Also I could not set bgl.glDisable(bgl.GL_DEPTH_TEST) as polygons are drawn in 2d.

**Comment by nutti** [comment]
Thanks for your feedback!
I applied your requests.

> I tried to change to bgl.glVertex3f(co1, co2, co3) but I got exception.
> Also I could not try to set bgl.glDisable(bgl.GL_DEPTH_TEST) as polygons are drawn in 2d.

This is because the compatibility module does not support these API.
I added these API now, so you can try them now :)

**Comment by mifth** [comment]
Sorry, I could not handle your code. I had some errors. But I have found an example where is no flickering of polygons. Just press play in my scene.

![image](https://user-images.githubusercontent.com/2251298/108354289-4cd93c80-71fa-11eb-93f5-a30cff2f3d1c.png)


[tmp2.zip](https://github.com/nutti/Magic-UV/files/6002591/tmp2.zip)

**Comment by nutti** [comment]
@mifth 

Thanks for the reference code.
I applied this code to the ad-on and works fine for me.
Could you try the add-on again.
https://github.com/nutti/Magic-UV/archive/issue_143.zip

The flicking issue comes from the procedures to do occlusion culling manually.
I hope the current code works for your environment.

**Comment by mifth** [comment]
@nutti 
Awesome! All looks amazing! Thank you a lot.

![image](https://user-images.githubusercontent.com/2251298/108485460-faf1ee80-72ad-11eb-8cb9-26472a1084e3.png)

**Comment by nutti** [comment]
@mifth 

Thanks for your feedback and help.
I will merge this feature soon.

**Comment by mifth** [comment]
Thank you too. Awesome tools!

**Comment by nutti** [comment]
This feature is now merged to master branch.
Thanks for your help @mifth .
