### ISSUE TITLE
Magic UV crash

### ISSUE THREAD

**Issue by zimmerer-SF** [nutti/Magic-UV#144]
When I use Smart UV Project one out of 10 time it crashes Blender.  Attached is the crash text.
[tudor_house_1.crash.txt](https://github.com/nutti/Magic-UV/files/5788683/tudor_house_1.crash.txt)

**Comment by nutti** [comment]
Smart UV project is not the part of Magic UV.

Please redirect to Blender bug tracker system.
https://developer.blender.org/
