### ISSUE TITLE
doesnt work in 2.93

### ISSUE THREAD

**Issue by yourherobby** [nutti/Magic-UV#147]
it doesnt work in 2.93, go to object copy/paste uv and list of uv is empty. also plenty of error !

**Comment by nutti** [comment]
@yourherobby 

Could you give me the error log?
I think this relates to https://github.com/nutti/Screencast-Keys/issues/45

**Comment by nutti** [comment]
I found that this is a same issue as I wrote above.
This bug is now fixed.
