### ISSUE TITLE
Align UV Cursor Behaviour Issues

### ISSUE THREAD

**Issue by gohde** [nutti/Magic-UV#148]
Tested on Blender 2.92.0, install via preferences. 
Windows 10 64-bit. amd cpu, nvidia graphics

Magic UV > Editor Enhancement > Align UV Cursor

Firstly it seems that "UV" and "UV (Selected)" seems to swapped in their behaviour. "UV (Selected)" seems to behave like "Texture" and "UV" aligns the cursor to the selected UV's.

Secondly aligning to a single selected vertex or edge does not seems to work, it needs full polygons.

![2021-03-11 00_52_57-Blender](https://user-images.githubusercontent.com/1173400/110714753-48ee7800-8204-11eb-9c79-2877a09ea75a.png)

**Comment by nutti** [comment]
@gohde 

Thanks for your report. I fixed it.
Please note that when the selected vertex is located at the border of UV island with UV Sync Selection enabled, this feature still fails because of the Blender's specification.
