### ISSUE TITLE
Typo in the Wiki "Copy/Pate UV"

### ISSUE THREAD

**Issue by SpechtMagnus** [nutti/Magic-UV#149]
**System Information**
*irrelevant*

**Expected behavior**  
Paste is pselled Paste insted of Pate

**Description about the bug**  
Just a simple typo. In the Wiki on the Tutorial Page it says "Copy/**Pate** UV"

**Comment by nutti** [comment]
This is now fixed.
I will reflect this to the wiki as well after v6.6 is released.
