### ISSUE TITLE
Copy/Pasting a UV map from a mesh variant results in a distorted map

### ISSUE THREAD

**Issue by ghost** [nutti/Magic-UV#155]
**System Information**
  
* OS: Windows 10.0.19044
* Blender version: 3.1.2
* Add-on version: 6.5.0

**Expected behavior**  
The target UV map is copied over to another mesh without distortions.

**Description about the bug**  
In our project, we have succesfully used UV Copy/Paste feature for all other models with similar features, but for some reason the attached model has distortions when we copy the Wide map from the Wide mesh to the Base mesh. The vertex order is the same as you can see from the created Shape Key (using Join as Shapes).

**Screenshots/Files** [Optional]  
![blender_EvDpz90GnQ](https://user-images.githubusercontent.com/1652895/164700282-6ec7c6ed-27f7-48dd-938e-8b7fb57aa52e.png)

[uv-bug.zip](https://github.com/nutti/Magic-UV/files/8540270/uv-bug.zip)

**Comment by nutti** [comment]
@mystrdat 

Sorry for the late reply.
Is it possible to share a base model?

Copy/Paste UV only refers UV coordinate not vertex coordinate.
So this is a bit weird behavior.

**Comment by nutti** [comment]
@mystrdat 

Sorry, I found the base mesh in the same .blend file.
I checked the UV coordinate and confirmed that this behavior is the expected one.

As I said on the previous post, Copy/Paste UV only refers UV coordinate not vertex coordinate.
