### ISSUE TITLE
Copy/Pasting UV islands with slight variations causes a crash (load wheel)

### ISSUE THREAD

**Issue by RecklessJames** [nutti/Magic-UV#157]
**System Information**
  
* OS: Windows 10
* Blender version: 2.90
* Add-on version: 6.6

**Expected behavior**  
Attempting to paste a copied UV island to another island.

**Description about the bug**  
Freezes with infinite loading, requiring forced shutdown of program using Task Manager.

**Screenshots/Files** [Optional] 
![1](https://user-images.githubusercontent.com/12752293/171758046-d6bef519-2808-4379-a255-7c54f0b9544a.png)
![2](https://user-images.githubusercontent.com/12752293/171758047-07a2fa8d-84da-4a4e-97f0-bc17e5aa88c1.png)

**Additional comments** [Optional]
It only works properly if both UV islands are literally 100% the exact same position of faces... basically for islands where I wouldn't need to use copy/paste to begin with, making this feature pretty much pointless if this cannot be resolved, sadly.

**Comment by nutti** [comment]
Thanks for your report.
This issue is now fixed.
