### ISSUE TITLE
Copy/Paste UV causes "KeyError"

### ISSUE THREAD

**Issue by RedMser** [nutti/Magic-UV#158]
**System Information**
  
* OS: Windows 10
* Blender version: 3.2.0 and 3.3.0
* Add-on version: 6.6.0

**Description about the bug**  
- Open factory startup scene, select cube
- Add a second UVMap to it
- Edit Mode -> select all
- Press U -> Copy/Paste UV -> Copy Default -> UVMap
- Press U -> Copy/Paste UV -> Paste Default -> UVMap.001

```
Info: Copy UV coordinate (UV map: UVMap)
Info: 6 face(s) are copied

Traceback (most recent call last):
  File "blender-3.2.0-windows-x64\3.2\scripts\addons\magic_uv\op\copy_paste_uv.py", line 466, in execute
    face_count = len(props.src_info[list(dest_info.keys())[0]])
KeyError: 'UVMap.001'
Info: Paste UV coordinate (UV map: UVMap.001)
Error: Python: Traceback (most recent call last):
  File "blender-3.2.0-windows-x64\3.2\scripts\addons\magic_uv\op\copy_paste_uv.py", line 466, in execute
    face_count = len(props.src_info[list(dest_info.keys())[0]])
KeyError: 'UVMap.001'
```

Commenting out the relevant lines makes this function of the addon work fine.

**Comment by nutti** [comment]
@RedMser 

Thanks. This issue is now fixed.
