### ISSUE TITLE
Error on undo in UV Bounding Box mode

### ISSUE THREAD

**Issue by mouurusai** [nutti/Magic-UV#159]
**System Information**
  
* OS: Windows 10 19043
* Blender version: 3.2.0
* Add-on version: 6.6.0

**Expected behavior**  
ctrl+z undo previous action

**Description about the bug**  
Undo action in UV Bounding Box mode cause an error:
```
Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\addons\magic_uv\op\uv_bounding_box.py", line 802, in modal
    self.__update_uvs(context, props.uv_info_ini, trans_mat)
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\addons\magic_uv\op\uv_bounding_box.py", line 761, in __update_uvs
    uv_layer = bm.loops.layers.uv.verify()
ReferenceError: BMesh data of type BMesh has been removed
```

**How to reproduce**
Select object with uv data
Switch to edit mode
Select all in 3d view
Select all in UV editor
Open UV Magic panel
Check on "UV Bounding Box"
Click "Show" button
Press ctrl+z or undo in edit menu

**Screenshots/Files** [Optional]  
[Scene.zip](https://github.com/nutti/Magic-UV/files/9129285/Scene.zip)
![image](https://user-images.githubusercontent.com/13837158/179443663-38e67519-657e-43f1-a917-3457cb7d218c.png)

**Comment by nutti** [comment]
This issue is now fixed.
