### ISSUE TITLE
AttributeError in 6.5.0-6.6.0

### ISSUE THREAD

**Issue by EugeneDudavkin** [nutti/Magic-UV#161]
**System Information**
* OS: [Windows-10-10.0.19044-SP0 64 Bits]
* Blender version: [2.93.7] and [3.2.1]
* Add-on version: [6.5.0] and [6.6.0]

**Description about the bug**  
If select non mesh object and hit F3 -> Error
```
Python: Traceback (most recent call last):
  File "...\blender-3.2.1-windows-x64\3.2\scripts\addons\magic_uv\op\copy_paste_uv_object.py", line 148, in draw
    uv_maps = compat.get_object_uv_layers(obj).keys()
  File "...\blender-3.2.1-windows-x64\3.2\scripts\addons\magic_uv\utils\compatibility.py", line 121, in get_object_uv_layers
    return obj.data.uv_layers
AttributeError: 'Camera' object has no attribute 'uv_layers'
```

**Comment by nutti** [comment]
This issue is fixed by Blender official patch.
https://developer.blender.org/rBA4b25801f640ee49f49c63d4de6871504236ce6b7

The patch has already merged to this repo.
https://github.com/nutti/Magic-UV/commit/545652261e9c59ffa02ed29333b4a0bf4c667dbb

**Comment by nutti** [comment]
Sorry this error is different from the Blender official patch.
But this issue is now fixed.
