### ISSUE TITLE
Import UVMap from an external model

### ISSUE THREAD

**Issue by 1NightVision1** [nutti/Magic-UV#162]
**Description about the feature**  
When on import section there would be a "UV Map Import" that will let you choose a model, using UV compatibile models as extension (e.g. FBX), and possibly let you choose what UVMap to import to the active object. Possibly it would allow for DataTransfer of the UVMap importe, to a different geometry, if that's the case. This would be an import variance basically, of the already existing "Copy UV" that's inside the N Panel.

**Are you willing to contribute about this feature. (Yes/No)**  
No, I'm a noob Serpens user

**Additional comments** [Optional]
This is not actually for my workflow, but i think this would be a useful feature for some, and i think it would not take that much to implement, i think... Also i like the idea of having a bank of UV that you can import without having to manually import the file and then do the copy. It's a tiny thing, i know, but hey, add-ons are for speed am i right?

**Comment by 1NightVision1** [comment]
As i said on the Additional Comments, this is not actually something i would use, so... not sure if there's any advantages. The main thing was that, instead of importing the object, then use the "Copy UV" button on the panel, the option on the importer (which can be added to the addon it self) would make all of this for you,  no object being added to the file. The original idea of the dude i was talking to was of an FBX file, or with another UV compatible extension, that is used purely and only for UV. I don't really know the general use of this, since usually you don't want to change UV again and again, but this was his idea, being able to add an already existing uv, to the model. The model remains always the same, but the uv is imported just like anything else.
If it's too confusing, or if you think it's not useful don't worry about it (aka, you can close the post if you want) , don't want to take time and efforts for a useless feature. Thanks for the reply anyway :)

**Comment by nutti** [comment]
@1NightVision1 

Thanks for your following up.
After finishing other tasks, we will tackle this issue.
So please wait patiently...

**Comment by nutti** [comment]
@1NightVision1 

Does it mean that you want to transfer UV map to the other meshes via custom UV map file?
If UV coordinates are same among objects topologically, you can Copy/Paste UV coordinates by using the island based Copy/Paste UV.
