### ISSUE TITLE
Align UV Cursor did not convert values for Pixel Coordinates

### ISSUE THREAD

**Issue by EugeneDudavkin** [nutti/Magic-UV#164]
**System Information**
  
* OS: Windows 10
* Blender version: 3.3.1
* Add-on version: 6.6.0

**Description about the bug**  
Align UV Cursor tool did not convert values (2) if Pixel Coordinates is checked (1)

![AlignUVCursor](https://user-images.githubusercontent.com/87300864/203984356-a5b33466-e63e-4a29-ae29-7c11fd16ea53.png)

**Comment by nutti** [comment]
Sorry for the late response.
This issue is now fixed.
