### ISSUE TITLE
blender crash when copy paste

### ISSUE THREAD

**Issue by mhanna12** [nutti/Magic-UV#173]
**System Information**
  
* OS: [ Windows 11]
* Blender version: [4.1.1]
* Add-on version: [6.7.0]

**Expected behavior**  
*to copy uv island and paste it on another uv island*

**Description about the bug**  
*so i copy uv island to another uv island but its make blender crash i reopen it many times and disable and enable the addon but still have the same problem
![Screenshot (1266)](https://github.com/user-attachments/assets/3600c752-ea92-4500-8061-00b250907861)
*

**Screenshots/Files** [Optional]  
*It is good to solve the bug if you attach the screenshots or .blend file.*

**Additional comments** [Optional]

**Comment by mifth** [comment]
Thanks. Is it possible to provide a blend file with this piece of the mesh? And what buttons you pressed?

**Comment by mhanna12** [comment]
> Thanks. Is it possible to provide a blend file with this piece of the mesh? And what buttons you pressed?

before i send any file do u think its because of the topology of the mesh itself or it doesnt matter on the uvs?

**Comment by mhanna12** [comment]
so here is the file so please look it up https://we.tl/t-JE33R2lSyc

**Comment by mifth** [comment]
Thanks. I'll upload the file as zip here.
[Crash.zip](https://github.com/user-attachments/files/17852773/Crash.zip)

**Comment by mifth** [comment]
I didn't get any crashes. All works as expected.

For your case you could try UVTransfer feature.

1 Hide othe polygons
2 select 2 polygons like on the first screenshot below and Copy.
3 Select 2 polygons the same way and Paste.
3 Set InvertNormals=True

![image](https://github.com/user-attachments/assets/f7b03fc2-09e9-41e0-8d3e-e69700080032)
![image](https://github.com/user-attachments/assets/fbb12610-cecb-4c80-8234-22bb69f4c563)
![image](https://github.com/user-attachments/assets/9214d137-c2ee-4489-8148-1509c110b7e4)

**Comment by mhanna12** [comment]
ill check it and see if it'll work for me but i by mistake sent u file with the materials which i dont own so please dont use them

**Comment by mifth** [comment]
Sure, I've deleted the zip file.

**Comment by mhanna12** [comment]
sry for the late reply but thanks its worked

**Comment by mhanna12** [comment]
sry for the late reply but thanks its worked

**Comment by nutti** [comment]
Thank you @mifth for your support.
