### ISSUE TITLE
New feature: Texture Wrap

### ISSUE THREAD

**Issue by nutti** [nutti/Magic-UV#24]
This is @eXKR request.
http://blenderartists.org/forum/showthread.php?348421-Addon-Copy-and-Paste-UV-Coordinates&p=2875898&viewfull=1#post2875898

This feature exists in Hammer.
https://www.youtube.com/watch?v=Sd3fVqaWTY0&t=3m32s

Paste to adjacent polygon with UV coordinate automatically shifts. UV coordinates would shift according with polygon distance.

**Comment by mifth** [comment]
Yes, interesting feature.
I guess there should be relative sizes according to faces lengths and uvs lengths.

Possibly this feature can be made as selection sequence. First selected face can be source. Other selected faces are destination.

But you will need to get connected certs and sort them a bit.
Also what about triangles and ngons?

**Comment by nutti** [comment]
> I guess there should be relative sizes according to faces lengths and uvs lengths.

Yeah, this will be a basic algorithm when implementing this feature.
And, I finished this.
https://github.com/nutti/Copy-And-Paste-UV/commit/85f43b78f6379cd0a60b285a141d3972d3073b9d

> Possibly this feature can be made as selection sequence. First selected face can be source. Other selected faces are destination.

I think so.
I can support selection sequence with few code change.

> Also what about triangles and ngons?

This is a problem in current implementation.
Current implementation is limited to quad polygons.
If you use triangles/ngons, the result will be unexpected.

**Comment by nutti** [comment]
OK, support multiple pasting with same algorithm used in selection sequence copy/paste.

**Comment by nutti** [comment]
@mifth

I have no idea about issue mentioned below link.
http://blenderartists.org/forum/showthread.php?348421-Addon-Copy-and-Paste-UV-Coordinates&p=2895600&viewfull=1#post2895600

This problem will be solved, If I can get 2D vector of difference position between each verts.

Do you have any idea?

**Comment by mifth** [comment]
A face has a normal and tangent. Posibly, they can help to convert 3d coordinates to 2d.
I checked these utils but nothing was found:
http://www.blender.org/api/blender_python_api_2_75_release/mathutils.geometry.html
http://www.blender.org/api/blender_python_api_2_75_release/mathutils.html

I think it's better to ask at http://blender.stackexchange.com/ for help.

**Comment by nutti** [comment]
I questioned this problem for 3 month ago, but there is no answer.

Because I have no idea about this feature, so I will hold this feature.

**Comment by nutti** [comment]
Implemented this feature.

**Comment by schroef** [comment]
Which rv is this? i dont see this update in the list on main page?

**Comment by nutti** [comment]
this feature is already in develop branch.
but i forget updating the readme.md file.
i will update it later.

thanks for reporting.

**Comment by schroef** [comment]
OKay i also saw something about v5 done, but i dont see that neither??? But that is probalby for version 5 i guess. I just looked at it again and you seem to use labels/tags. Thats quite clever

**Comment by nutti** [comment]
> I just looked at it again and you seem to use labels/tags. Thats quite clever, but arent you applying to much tags? I see so many filter options now

Ah, sorry it seems that milestone is already gone.

https://github.com/nutti/Magic-UV/milestone/10

But I will add one more feature as below.
#59 

I'm now looking into Blender's source code to understand what is sculpt.

**Comment by schroef** [comment]
You mean UV sculpt?

**Comment by nutti** [comment]
@schroef 

That's right.
But this feature is different from UV sculpt feature.
It will be able to run on View3D.

**Comment by schroef** [comment]
aha i remember some sort of addon which did the same. It worked a bit tedious and moving it was done quite harsh.

Perhaps add additional keys like shift to soft move it arround just like when translation objects, if that is possible.
