### ISSUE TITLE
Future works for this plugin

### ISSUE THREAD

**Issue by nutti** [nutti/Magic-UV#31]
@mifth , everyone

Hi,

This plugin becomes more powerful than first release, thanks to many user's feedback.
And there are many requests about this plugin.

However, there is a unrelated request about this add-on, but will be useful feature.
- Texture Lock
- Transform texture island by bounding box
- Move UV coordinate in the selected polygon

Above request is related UV or Image.
I'm annoying that should theseadd-on include above features or setup new project.
If above features are included in this add-on, add-on name should be changed.

Which do you want to do about this add-on?
If I rename this add-on or setup new project, what name is best?

Thanks!

**Comment by mifth** [comment]
Hi.
where i can see these requests?

I think we can extend other uv tools. not only copy/paste.

you can rename the addon like uvtools/superuv/magicuv or any orher name where we can put other uv tools.

**Comment by nutti** [comment]
@mifth 

Hi,

> where i can see these requests?

You can see this add-on's thread on Blender Artist.

> you can rename the addon like uvtools/superuv/magicuv or any orher name where we can put other uv tools.

Maybe UV tools is simple and clear.
If some request is supported, we should rename this add-on.

**Comment by mifth** [comment]
Ok, i‘ll check ba thread asap. i‘m on vacation right now for about two weeks.

Uv tools sounds good. i hope nobody uses this name already.

**Comment by nutti** [comment]
@mifth 

Thanks.
I'm now tackling **Texture Wrap** #24  and **Copy/Paste N polygon to M polygon ** #23.
I think **Texture Lock** and **Move UV coordinate in the selected polygon** seems to be difficult.
I will make issue about these features.

Have a nice holiday!

**Comment by nutti** [comment]
And, I will refactor current code for v4.0.
Current code change Object mode to Edit mode frequently.

**Comment by nutti** [comment]
@mifth 

Hi,

IMO, **Copy/Paste UVs** is minor version of **Copy/Paste UVs (Selection Sequence)**.
So, I will remove current feature **Copy/Paste UVs** and rename **Copy/Paste UVs (Selection Sequence)** as **Copy/Paste UVs**.

What do you think?

**Comment by mifth** [comment]
Hi.
i think they work a bit differently. as copy/paste can copy 1000 uvs with one click.

I would leave it so that a user could have a choice.
but this is up to you, as you are the main developer.

**Comment by nutti** [comment]
@mifth 

> as copy/paste can copy 1000 uvs with one click.

Oh.., I could not assume above usage.

OK, I will not remove this feature.
However, I will refactor these feature because current implementation changes object mode to edit mode many times, and vice versa.

**Comment by nutti** [comment]
And I will import another add-on **Texture Projection** to this plugin I made before.
http://blenderartists.org/forum/showthread.php?371958-Add-on-Texture-Projection
https://github.com/nutti/Texture-Projection

I think this is related to UV tools.

**Comment by mifth** [comment]
Great!

**Comment by nutti** [comment]
Texture Projection is very similar to **UV Project** modifier.
And, I could not render texture with bgl package. (I didn't get this problem)

So, I temporary removed **Texture Projection** from v4.0.

**Comment by nutti** [comment]
This add-on will be included to Blender 2.79 release.
And I will continue to maintain this add-on.
Request and bug fix will be accepted after release on Blender 2.79.

Repository on GitHub will be used for development version.
I think this issue is no longer need, so closing now.

Thanks for great support, especially best contributor @mifth .

**Comment by mifth** [comment]
Hi!
Great news. Will be included 4.4 version into the blender?

**Comment by mifth** [comment]
Ah... Nevermind. 4.3 is great! :)

**Comment by nutti** [comment]
Yes, v4.3 will be included in Blender 2.79 release.

https://developer.blender.org/rBA8a17c01627bae97a66a237d5ab3cfd19c8f7adc1

Thanks for your long support.
