### ISSUE TITLE
New feature: Texture Lock

### ISSUE THREAD

**Issue by nutti** [nutti/Magic-UV#33]
@eXKR requests this feature in [Blender Artist](http://blenderartists.org/forum/showthread.php?348421-Addon-Copy-and-Paste-UV-Coordinates&p=2875898&viewfull=1#post2875898)

Paste to adjacent polygon with UV coordinate automatically shifts.
The polygon to paste doesn't need to be the adjacent but anyone, that means the UV coordinates would shift according with polygon distante.
It's a feature in **Creator** .

https://www.youtube.com/watch?v=QH3G...youtu.be&t=103

**Comment by mifth** [comment]
Is this the same if we copy one face then paste its uvs into other faces?

**Comment by nutti** [comment]
Completed to develop this feature.
I think this feature fixed UV coordinate in 3D View coordinate.

https://github.com/nutti/Copy-And-Paste-UV/commit/9bec63fa76fd5241df2891f50c556153b82dc06b

**Comment by nutti** [comment]
eXKR is commented about this feature in Blender Artists.

http://blenderartists.org/forum/showthread.php?391573-Add-on-Magic-UV-v4-0-(Copy-Paste-UV)&p=3043493&viewfull=1#post3043493

Requested feature is same as **Preserve UV** in 3dsmax.

**Comment by nutti** [comment]
I finished developing this feature.

https://github.com/nutti/Magic-UV/commit/38e5def571e975da5404e0df657ea51fd6ae1bde#diff-f3e47dcd0c0acf208244a700d64f8c0c

I will open new issue when new problem is arisen.
