### ISSUE TITLE
New feature: Move UV coordinate in the selected polygon

### ISSUE THREAD

**Issue by nutti** [nutti/Magic-UV#35]
@eXKR requests this feature in [Blender Artist](http://blenderartists.org/forum/showthread.php?348421-Addon-Copy-and-Paste-UV-Coordinates&p=2879550&viewfull=1#post2879550)

Fit to bounding box of polygon.

**Comment by mifth** [comment]
I don't get this feature clear. Polygon can have any size. Texture has size from 0 to 1.
Also blender has "reset" feature in the u menu which make the same as on video.

But possibly I misunderstood something?

**Comment by nutti** [comment]
@mifth 

I checked this request again.
However I didn't get understand this feature too.
I think "reset" feature meets this requirement.

I will confirm @eXKR about this request at Blender Artist.

**Comment by mifth** [comment]
Sure. I don't get this too.

**Comment by nutti** [comment]
I posted question about this feature on Blender Artists.
However @eXKR who requested this feature, may not see this add-on's thread.

If @eXKR will not respond this question until January, I will remove this feature.

**Comment by mifth** [comment]
No problem.

**Comment by nutti** [comment]
It seems to be no reaction about this feature.
So, I will close this issue...
