### ISSUE TITLE
Other features of Modo 901

### ISSUE THREAD

**Issue by mifth** [nutti/Magic-UV#36]
It would be great to get other features from Modo 901 which blender does not have.
https://vimeo.com/127917390
https://vimeo.com/124320824
Like align, relax.

Feature future... :dancer:

**Comment by nutti** [comment]
Thanks for your suggestion.
It's interesting feature.
And, I have a question.

Is *align* feature something same as UV Align\Distribute add-on?
http://blenderartists.org/forum/showthread.php?340206-Add-On-UV-Align-Distribute/

Is there any new features from 2nd video?
I think it only shows transfer UV feature already made.

**Comment by nutti** [comment]
@mifth

Are these requests not abondaned?

**Comment by mifth** [comment]
I think no any stuff is needed. At the videos. I close it.

**Comment by nutti** [comment]
@mifth 

OK, thanks.
If you have another request in future, please make new issue :)
