### ISSUE TITLE
Pack the same UV Islands.

### ISSUE THREAD

**Issue by mifth** [nutti/Magic-UV#41]
Hi.

I have a feature request. :)

Pack the same UV Islands. Modo and Houdini can do this. But blender misses such a feature.

Here is example:
http://i.imgur.com/UhV5VMy.png - Original Uvs before packing
http://i.imgur.com/crNpcwB.png - Packing like in Blender
http://i.imgur.com/lPv0PEC.png - Packing with the same UV Islands. Very useful to pack many UVs!

In blender packing goes with Ctrl+P shortcut in the UV Editor. or in the menu UVs->Pack.
Packing works for selected UV Islands.

It would be super cool feature.

Possible implementation:
- Find all UV Islands
- Check every UV Island size(x and y).
- Check every UV Island center position
- If some UV Islands have the same quantity ov vertices and the same UV Size and the same UV Center then they are indentical. And only one UV Island can be selected. All other identical can be deselected.
- After packing just copy uvs to identical UV Islands.

**Comment by nutti** [comment]
@mifth 

It looks great.
This feature also is picked up below link.
https://wiki.blender.org/index.php/Dev:Ref/GoogleSummerOfCode/2016/Ideas

Should I contact them if we develop this feature?

**Comment by nutti** [comment]
@mifth 

Hi,
I made a prototype about this feature with standalone script.
Does this script meet your requirement?
If this script meet requirement, I will develop as a add-on.

```python
import bpy
import bmesh
from mathutils import Vector
from math import fabs

bpy.ops.mesh.select_all()
bpy.ops.mesh.select_all()

bpy.context.scene.tool_settings.uv_select_mode = 'ISLAND'
obj = bpy.context.active_object
bm = bmesh.from_edit_mesh(obj.data)
uv_layer = bm.loops.layers.uv.verify()

island_info = []
uv_island_lists = []

# get all UV islands
while True:
    bpy.ops.uv.select(extend = False, location = (0,0))
    selected_uvs = []
    for f in bm.faces:
        for l in f.loops:
            if l[uv_layer].select:
                selected_uvs.append({'uv': l[uv_layer].uv, 'loop_idx': l.index})
    if len(selected_uvs) == 0:
        break
    uv_island_lists.append(selected_uvs)
    bpy.ops.uv.hide()

# get information about each island
for island in uv_island_lists:
    info = {}
    max = Vector((-10000000.0, -10000000.0))
    min = Vector((10000000.0, 10000000.0))
    ave = Vector((0.0, 0.0))
    for uv_data in island:
        uv = uv_data['uv']
        if uv.x > max.x:
            max.x = uv.x
        if uv.y > max.y:
            max.y = uv.y
        if uv.x < min.x:
            min.x = uv.x
        if uv.y < min.y:
            min.y = uv.y
        ave = ave + uv
    ave = ave / len(island)
        
    info['center'] = ave
    info['size'] = max - min
    info['num_uv'] = len(island)
    info['group'] = -1
    info['uvs'] = island
    
    island_info.append(info)

# check if there is same island
num_group = 0
while True:
    for isl in island_info:
        if isl['group'] == -1:
            break
    else:
        break
    isl['group'] = num_group
    for isl_2 in island_info:
        if isl_2['group'] == -1:
            center_matched = (fabs(isl_2['center'].x - isl['center'].x) < 0.001) and (fabs(isl_2['center'].y - isl['center'].y) < 0.001)
            size_matched = (fabs(isl_2['size'].x - isl['size'].x) < 0.001) and (fabs(isl_2['size'].y - isl['size'].y) < 0.001)
            num_uv_matched = (isl_2['num_uv'] == isl['num_uv'])
            if center_matched and size_matched and num_uv_matched:
                isl_2['group'] = num_group
    num_group = num_group + 1

loop_lists = [l for f in bm.faces for l in f.loops]

# copy/paste UV among same island
for gidx in range(num_group):
    group = list(filter(lambda i:i['group']==gidx, island_info))
    if len(group) <= 1:
        continue
    for g in group[1:]:
        for (src, dest) in zip(group[0]['uvs'], g['uvs']):
            loop_lists[dest['loop_idx']][uv_layer].uv = loop_lists[src['loop_idx']][uv_layer].uv
         
```

Thanks.

**Comment by mifth** [comment]
Hi.

I tried to run it. But I could not understand what it does.
I think you can use **bpy.ops.uv.pack_islands(margin=0.272269)** function.

I think yo can do like this:
- Parse selected faces/uvs
- Deselect The same(overlapped) uv islands
- Pack unique islands with **bpy.ops.uv.pack_islands(margin=0.272269)**
- copy uvs from packed unique uvs to deselected uvs. 

Here is test scene:
[temp_pack.blend.zip](https://github.com/nutti/Magic-UV/files/177743/temp_pack.blend.zip)
It has 3 cubes and 3 spheres with the same (overlapped) uvs.

Right now blender packing looks like this:
![selection_036](https://cloud.githubusercontent.com/assets/2251298/13844866/81c68a16-ec4d-11e5-832c-d2f2821e84ba.png)

And we need to get sometthing like this:
![selection_037](https://cloud.githubusercontent.com/assets/2251298/13844885/a1d9a25c-ec4d-11e5-890f-7fe71dbccb53.png)

**Comment by nutti** [comment]
@mifth 

Hi,

Ah..., I misunderstood your intention.
I revised script.

```python
import bpy
import bmesh
from mathutils import Vector
from math import fabs

bpy.ops.mesh.select_all(action='SELECT')

bpy.context.scene.tool_settings.uv_select_mode = 'ISLAND'
obj = bpy.context.active_object
bm = bmesh.from_edit_mesh(obj.data)
uv_layer = bm.loops.layers.uv.verify()

island_info = []
uv_island_lists = []

# get all UV islands
while True:
    bpy.ops.uv.select(extend = False, location = (0,0))
    selected_uvs = []
    for f in bm.faces:
        for l in f.loops:
            if l[uv_layer].select:
                selected_uvs.append({'uv': l[uv_layer].uv, 'loop_idx': l.index})
    if len(selected_uvs) == 0:
        break
    uv_island_lists.append(selected_uvs)
    bpy.ops.uv.hide()

# get information about each island
for island in uv_island_lists:
    info = {}
    max = Vector((-10000000.0, -10000000.0))
    min = Vector((10000000.0, 10000000.0))
    ave = Vector((0.0, 0.0))
    for uv_data in island:
        uv = uv_data['uv']
        if uv.x > max.x:
            max.x = uv.x
        if uv.y > max.y:
            max.y = uv.y
        if uv.x < min.x:
            min.x = uv.x
        if uv.y < min.y:
            min.y = uv.y
        ave = ave + uv
    ave = ave / len(island)

    info['center'] = ave
    info['size'] = max - min
    info['num_uv'] = len(island)
    info['group'] = -1
    info['uvs'] = island

    island_info.append(info)

# check if there is same island
num_group = 0
while True:
    for isl in island_info:
        if isl['group'] == -1:
            break
    else:
        break
    isl['group'] = num_group
    for isl_2 in island_info:
        if isl_2['group'] == -1:
            center_matched = (fabs(isl_2['center'].x - isl['center'].x) < 0.001) and (fabs(isl_2['center'].y - isl['center'].y) < 0.001)
            size_matched = (fabs(isl_2['size'].x - isl['size'].x) < 0.001) and (fabs(isl_2['size'].y - isl['size'].y) < 0.001)
            num_uv_matched = (isl_2['num_uv'] == isl['num_uv'])
            if center_matched and size_matched and num_uv_matched:
                isl_2['group'] = num_group
    num_group = num_group + 1

loop_lists = [l for f in bm.faces for l in f.loops]

bpy.ops.mesh.select_all(action='DESELECT')

# pack UV
for gidx in range(num_group):
    group = list(filter(lambda i:i['group']==gidx, island_info))
    for uv in group[0]['uvs']:
        bm.faces[loop_lists[uv['loop_idx']].face.index].select = True
        
bmesh.update_edit_mesh(obj.data)
bpy.ops.uv.select_all(action='SELECT')
bpy.ops.uv.pack_islands(margin=0.272269)

# copy/paste UV among same island
for gidx in range(num_group):
    group = list(filter(lambda i:i['group']==gidx, island_info))
    if len(group) <= 1:
        continue
    for g in group[1:]:
        for (src, dest) in zip(group[0]['uvs'], g['uvs']):
            loop_lists[dest['loop_idx']][uv_layer].uv = loop_lists[src['loop_idx']][uv_layer].uv

```

does it work correctly?

**Comment by mifth** [comment]
Wow! Awesome!
It works with the test file perfect. Good job!

The only issue I found that it works with some problems if i scale and rotate meshes. 
![selection_041](https://cloud.githubusercontent.com/assets/2251298/13897837/a5f8ad2c-edd0-11e5-832b-80a91e01dab7.png)

Here is the new test file:
[temp_pack_2.blend.zip](https://github.com/nutti/Magic-UV/files/180737/temp_pack_2.blend.zip)

**Comment by nutti** [comment]
@mifth 

This issue comes from failing to find UV island.
When meshes are rotated/scaled, UV islands are broken.

I may not understand what UV island is.
IMU, UV island is same to island when select UV by Island selection mode.
What do you think?

**Comment by mifth** [comment]
Every piece is UV Island. There is UVIsland selection in blender. Dunno know if it exists in python.
![selection_042](https://cloud.githubusercontent.com/assets/2251298/13898056/71f764ee-edd7-11e5-9c24-ccbfbac800c2.png)

**Comment by mifth** [comment]
You don't need to get 3d viewport into account. Only UVs are needed in this situation.

- you can ask here how to get uv islands http://blender.stackexchange.com/questions/ask
- This addon can find uv islands. You can grab its code https://wiki.blender.org/index.php/Extensions:2.6/Py/Scripts/UV/UV_Align_Distribution
It's in addon contribs. Like your CopyPasteUVs. At the same blender repo.

I attached it.
[uv_align_distribute.py.zip](https://github.com/nutti/Magic-UV/files/180758/uv_align_distribute.py.zip)

**Comment by nutti** [comment]
@mifth 

Ah, sorry.
I misunderstood again. You are right.

Maybe, ```by.ops.uv.select``` does not work correctly.
I will check again.

**Comment by nutti** [comment]
@mifth 

> This addon can find uv islands. You can grab its code

Great news.
I' ll try it.

**Comment by nutti** [comment]
@mifth 

Please this script.
I think it works correctly.

```python
import bpy
import bmesh
from mathutils import Vector
from math import fabs
from collections import defaultdict

bpy.ops.mesh.select_all(action='SELECT')

bpy.context.scene.tool_settings.uv_select_mode = 'ISLAND'
obj = bpy.context.active_object
bm = bmesh.from_edit_mesh(obj.data)
uv_layer = bm.loops.layers.uv.verify()

island_info = []
uv_island_lists = []

# get all UV islands
def get_island_1(bm, uv_layer):
    uv_island_lists = []
    while True:
        bpy.ops.uv.select(extend = False, location = (0,0))
        selected_uvs = []
        for f in bm.faces:
            if f.select:
                for l in f.loops:
                    if l[uv_layer].select:
                        selected_uvs.append({'uv': l[uv_layer].uv, 'loop_idx': l.index})
                        l[uv_layer].select = False
        if len(selected_uvs) == 0:
            break
        uv_island_lists.append(selected_uvs)
        bpy.ops.uv.hide()
    return uv_island_lists

face_to_verts = defaultdict(set)
vert_to_faces = defaultdict(set)
current_island = []

for f in bm.faces:
    for l in f.loops:
        id = l[uv_layer].uv.to_tuple(5), l.vert.index
        face_to_verts[f.index].add(id)
        vert_to_faces[id].add(f.index)


def get_island_2(bm, uv_layer):
    global face_to_verts
    global vert_to_faces
    global current_island

    def parse_island(bm, face_idx, faces_left):
        global face_to_verts
        global vert_to_faces
        global current_island
        if face_idx in faces_left:
            faces_left.remove(face_idx)
            for l in bm.faces[face_idx].loops:
                current_island.append({'uv': l[uv_layer].uv, 'loop_idx': l.index})
            for v in face_to_verts[face_idx]:
                connected_faces = vert_to_faces[v]
                if connected_faces:
                    for cf in connected_faces:
                        parse_island(bm, cf, faces_left)
    
    
    
    
    uv_island_lists = []
    faces_left = set(face_to_verts.keys())
    while len(faces_left) > 0:
        current_island = []
        face_idx = list(faces_left)[0]
        parse_island(bm, face_idx, faces_left)
        print(len(current_island))
        uv_island_lists.append(current_island)
    
    return uv_island_lists

uv_island_lists = get_island_2(bm, uv_layer)

print(len(uv_island_lists))


# get information about each island
for island in uv_island_lists:
    info = {}
    max = Vector((-10000000.0, -10000000.0))
    min = Vector((10000000.0, 10000000.0))
    ave = Vector((0.0, 0.0))
    for uv_data in island:
        uv = uv_data['uv']
        if uv.x > max.x:
            max.x = uv.x
        if uv.y > max.y:
            max.y = uv.y
        if uv.x < min.x:
            min.x = uv.x
        if uv.y < min.y:
            min.y = uv.y
        ave = ave + uv
    ave = ave / len(island)

    info['center'] = ave
    info['size'] = max - min
    info['num_uv'] = len(island)
    info['group'] = -1
    info['uvs'] = island

    island_info.append(info)

# check if there is same island
num_group = 0
while True:
    for isl in island_info:
        if isl['group'] == -1:
            break
    else:
        break
    isl['group'] = num_group
    for isl_2 in island_info:
        if isl_2['group'] == -1:
            center_matched = (fabs(isl_2['center'].x - isl['center'].x) < 0.001) and (fabs(isl_2['center'].y - isl['center'].y) < 0.001)
            size_matched = (fabs(isl_2['size'].x - isl['size'].x) < 0.001) and (fabs(isl_2['size'].y - isl['size'].y) < 0.001)
            num_uv_matched = (isl_2['num_uv'] == isl['num_uv'])
            if center_matched and size_matched and num_uv_matched:
                isl_2['group'] = num_group
    num_group = num_group + 1

loop_lists = [l for f in bm.faces for l in f.loops]

bpy.ops.mesh.select_all(action='DESELECT')

# pack UV
for gidx in range(num_group):
    group = list(filter(lambda i:i['group']==gidx, island_info))
    for uv in group[0]['uvs']:
        bm.faces[loop_lists[uv['loop_idx']].face.index].select = True


bmesh.update_edit_mesh(obj.data)

bpy.ops.uv.select_all(action='SELECT')
bpy.ops.uv.pack_islands(margin=0.272269)

# copy/paste UV among same island
for gidx in range(num_group):
    group = list(filter(lambda i:i['group']==gidx, island_info))
    if len(group) <= 1:
        continue
    for g in group[1:]:
        for (src, dest) in zip(group[0]['uvs'], g['uvs']):
            loop_lists[dest['loop_idx']][uv_layer].uv = loop_lists[src['loop_idx']][uv_layer].uv
```

**Comment by mifth** [comment]
Ok, I tested.

If I run the last test - it will be ok.
If i ran the first test - i'll get this:
![selection_001](https://cloud.githubusercontent.com/assets/2251298/13899579/eb420a86-ee02-11e5-9b21-f876abf05da9.png)

**Comment by nutti** [comment]
@mifth 

Thanks.
I think copy/paste UV is incorrect.
Revised copy/paste algorithm.

Try this one please.

[pack_uv_v4.py](https://gist.github.com/nutti/7c09e13954cb10ee89af)

**Comment by mifth** [comment]
Wow! It works pretty nice. See no issues.
Great work!

**Comment by nutti** [comment]
@mifth

OK,

Now, I will add this script as add-on.
Please wait...

**Comment by mifth** [comment]
Sure. I'll use it.

Could you add this to the tool:
- apply to selected faces only. Like we apply in copy/paste. So that unselected to be untouched.
- add margin to the tool history. So that we could change the value. As we added flip/rotate uvs.

Thank you a lot!

**Comment by mifth** [comment]
@nutti I tested the new packing on more heavy geometry (74000 faces). I noticed that the tool works very slow. Possibly you parse the same UV Islands many times?

Could you check it?
[temp_pack_4.blend.zip](https://github.com/nutti/Magic-UV/files/181223/temp_pack_4.blend.zip)

The blender packer takes about 2 seconds.

**Comment by nutti** [comment]
@mifth 

I think slow point is here.
Current code takes O(N^2) times. (N is loop size)
I will check this in including this feature to add-on.

```python
    for isl_2 in island_info:
        if isl_2['group'] == -1:
...
            if center_matched and size_matched and num_uv_matched:
...
                for f1 in face_sorted_1:
                    for f2 in isl_2['faces']:
...
```

**Comment by mifth** [comment]
Ok, thanks a lot.

**Comment by nutti** [comment]
@mifth 

At first, I merged this feature to this add-on.
You can use this feature from UV/Image Editro > UVs > Pack UV.

[![](http://img.youtube.com/vi/9gEK6hYdMFs/0.jpg)](https://www.youtube.com/watch?v=9gEK6hYdMFs)

Now, I'll tackle optimization.

**Comment by mifth** [comment]
Super cool.

**Comment by nutti** [comment]
@mifth 

I optimized algorithm.
Please try this one.

https://github.com/nutti/Magic-UV/archive/spike.zip

However, I think there is still room for more optimization.

**Comment by nutti** [comment]
@mifth 

From my environment, execution time is less than half of previous one.

**Comment by mifth** [comment]
@nutti 
I tested. It's become really faster. I rely on you as a super man. :)
Thank you a lot!

The only ask:
Is it possible not to deselect faces? So that to leave the same selection.

Super cool work. Thank you!

**Comment by nutti** [comment]
@mifth 

I tried further optimization.
It becomes more than about 10% higher performance on my machine.

https://github.com/nutti/Magic-UV/tree/spike

And I noticed that this most of execution time comes from parsing faces. (90% of execution time is used for this.)
This function has almost same algorithm which **UV Align Distribution** has.

https://github.com/nutti/Magic-UV/blob/spike/uv_magic_uv/muv_packuv_ops.py#L220

I will tackle to optimize again, but it may not be any more.

> The only ask:
> Is it possible not to deselect faces? So that to leave the same selection.

OK, I will revise this.

**Comment by mifth** [comment]
This all super cool! Thank you for optimization! I will use this awesome tool. :)

**Comment by mifth** [comment]
O, I found another one thing.
Could you add Rotate boolean from the blender's 
Pack tool? Also, Margin is 0.001 by default.

![selection_001](https://cloud.githubusercontent.com/assets/2251298/14061050/2b4a0794-f387-11e5-8c31-50a285cd7481.png)

**Comment by nutti** [comment]
@mifth

Try this one please.

https://github.com/nutti/Magic-UV/tree/spike

**Comment by nutti** [comment]
@mifth 

Hi,

Algorithm used at **UV Align Distribution** is very fast.
I think, there is no room for optimization about this function.

https://github.com/nutti/Magic-UV/tree/spike

Please confirm above add-on, rotate option is added and fix deselect issues.

**Comment by mifth** [comment]
Hi,

I'm on the phone now. I'll test when i get to a computer.
But i'msure you did all well.

**Comment by mifth** [comment]
Hi,

I'm on the phone now. I'll test when i get to a computer.
But i'm sure you did all well.

**Comment by mifth** [comment]
Hi.

I tested again.
If I select only 3-4 UV islands - it will be slow. I guess you parse all faces in the mesh. But you need to parse only Selected and Unhidden faces/uvs.

![selection_023](https://cloud.githubusercontent.com/assets/2251298/14079762/b5122bc8-f508-11e5-83b8-8a0469372ae4.png)

**Comment by nutti** [comment]
@mifth 

Ah, it's very easy bug.
I forgot initialize variables.
Please try new one.

https://github.com/nutti/Magic-UV/tree/spike

**Comment by mifth** [comment]
Hi,
I have just tested it. All works super cool now! Thank you a lot!

**Comment by nutti** [comment]
@mifth 

No, problem.
I will merge this revision to developer branch.

Thanks for testing.

**Comment by nutti** [comment]
@mifth 

Hi, 
I merged to develop branch.

**Comment by mifth** [comment]
Hi.

Thanks a lot! I close the issue.

**Comment by nutti** [comment]
@mifth 

Thanks for great feature request!

**Comment by schroef** [comment]
I just tried this with simple cubes. And it seems to place them random. Ive scaled the cube but the UV is the same. Does this also look at size in 3dview port?

**Comment by schroef** [comment]
Ahh only works when items are pre uv unwrapped and joined as shape. When meshes are unwrapped again, it doesnt pack them according to size and rotation, thats to bad.

**Comment by nutti** [comment]
it is not problem that it does not pack different size and rotation because it should not be packed when islands are not same.

I did not get your problem.

**Comment by schroef** [comment]
Well i thought that it would also look at islands when you unwrap and they are placed all around. BUt it seem it works only when they stacked already.

When you have exact the same UV islands and there are not stacked, they still we be packed like regular pack.

For instance take the sample scene provided earlier. Move a couple islands awya from the stack, then use MUV unpack. Packing will be done just like regular packing. But perhaps thats how its supposed to work. It isnt very clear actually, perhaps some more info or better workflow explanation?

**Comment by nutti** [comment]
This feature does **Pack UV** in Blender internal function at first.
Then, merge islands which are same shape.

so, if you want to merge same island, you can use this feature instead of original Pack UV.

**Comment by schroef** [comment]
Yes I understand, I thought it would also make the stacks of uv islands. But thats not the case. The user needs to manual or use align distribut to make tge stacks firsr. The packing using same works

**Comment by DKesserich** [comment]
If the script were to iterate through all the islands and do a Pack Islands op one at a time to basically expand each island to take up the whole UV space it would effectively auto-stack the islands. I've tested doing this manually and gotten pretty good results. Haven't taken the time to figure out the python steps yet.

**Comment by mifth** [comment]
Hey guys!
Did you try shotpacker addon? Can it stack uvs? May be we can check how it does the thing an add it to magic too?

**Comment by mifth** [comment]
Or we can leave this feature. As packing system is hardcore programming.

**Comment by mifth** [comment]
https://dropmefiles.com/YV1J9 
7 days. Only for study.

**Comment by mifth** [comment]
But maybe you can. As this is gpl. But you have to ask the author.
