### ISSUE TITLE
Visually way to see overlaped UVs and fliped UVs

### ISSUE THREAD

**Issue by nutti** [nutti/Magic-UV#43]
Request from @servapunk

http://blenderartists.org/forum/showthread.php?391573-Add-on-Magic-UV-v4-0-%28Copy-Paste-UV%29&p=3024628&viewfull=1#post3024628

> Another thing that I think blender really needs is a visually way to see overlaped uvs or/and fliped uvs. In other softwares uvs change their colors when they are overlap or flipped. I am not sure about the complexity of this request, I just want to know your opinion about this.

**Comment by mifth** [comment]
This work is not for the addon. This should add Blender developers.
Python will die using opengl. Performance will be super bad.

**Comment by nutti** [comment]
OK, I will tell him.

**Comment by nutti** [comment]
This is heavy task for this add-on.
So, I will reject this feature.

**Comment by mifth** [comment]
Yep. Right decision.
