### ISSUE TITLE
Merge add-on "World Scale UV"

### ISSUE THREAD

**Issue by nutti** [nutti/Magic-UV#44]
Request from @wuren @Mighty Pea @LDAsh

http://blenderartists.org/forum/showthread.php?391573-Add-on-Magic-UV-v4-0-%28Copy-Paste-UV%29&p=3014370&viewfull=1#post3014370

> In games (particularly ones with low resolution textures), you want to make sure every pixel is the same size, and the way you do that is to specify for instance: a 512x512 texture will be roughly 1mx1m ingame. 
> 
> This is also very useful (necessary) for environment creation where you would have multiple lightmapped areas connected together and want to avoid seams where they meet. If the texels in the lightmaps are always guaranteed to be the same size as every other, and with a little shuffling of the UVs, seams are almost non-existant.
> 
> This addon can do it (http://blenderartists.org/forum/show...World-Scale-UV) but I only really get it to work with 2.66/2.69 and when it first operates, it gives an error, and you need to actually try it a second time before it will function correctly. It doesn't seem like it will ever be updated anymore, unfortunately.
> 
> If a feature like this could be included, it would be wonderful.

**Comment by schroef** [comment]
How is this now realted to texture size. THe person was talking about game setting using 512x512 aka 1x1m. How will this texture size relative to real dimenions will be done?

**Comment by nutti** [comment]
@schroef 

This feature is not implemented because we are not permitted from @McBuff.

**Comment by McBuff** [comment]
Hold on a second guys. I'm the one that wrote that plugin some time ago.
I just got a mail because of the mention ( thanks @nutti ).

I don't know which version you guys tried using, but this one should be the latest.
http://www.mindonwaves.com/misc/blender-addon-archi-uv/

And sure, I'll give you permission to implement it, if you're willing to give me a little credit for it.

**Comment by nutti** [comment]
@McBuff 

Great news!
Thanks for giving me permission to implement your add-on.
And I would like to include and maintain your add-on as this add-on. Is it OK to do this?
Of course, I will remain your name as first author of this feature.

> I don't know which version you guys tried using, but this one should be the latest.
> http://www.mindonwaves.com/misc/blender-addon-archi-uv/

I have a question about your add-on.
Is below thread is abandoned? and is add-on on this thread older version? 
I also posted this topics to this thread and send message to @McBuff .

http://blenderartists.org/forum/showthread.php?275652-Addon-World-Scale-UV&p=3015682&viewfull=1#post3015682

Anyway, thank you very much to react to my sudden mention.

**Comment by schroef** [comment]
Okay that's awkward. Just taking the script and addin it???

**Comment by McBuff** [comment]
I'm a bit pressed for time for the moment, I'll give you a more expansive explanation later this day. ( 8pm GMT+1  or something)

**Comment by nutti** [comment]
@schroef

No, there is no license about McBuff's add-on.
If there is not license, we can not revise or redistribute because there is copyright.
We need to get permission from McBuff.

**Comment by nutti** [comment]
@McBuff

Thanks.
You don't need hurry.
If you don't want to agree this suggestion, please tell me.

**Comment by LDAsh72** [comment]
I just wanted to try, one more time, to clarify - that I never intended to request to simply throw this add-on (merge) into 'Magic UV', but to have written, from scratch, a similar function that can scale all (pre-established) UVs to a "real-world" metric, without trying to unwrap them again.

To clarify further about the 'World Scale UV' add-on - the earlier original script does this, but it spits an error and only works with 2.66a.  The latest script won't allow you to scale the UVs unless it (re)unwraps it first, which is not ideal, so either way, it's not wise to simply throw this into Magic UV because that won't do anything.  All we really need is the ability to scale UVs (which will be different layouts on different meshes) to a scale that is uniform (by texel) between everything, so that when we bake lightmaps or paint texels where these separate meshes meet, there won't be any noticeable seams.

Hopefully, finally, this makes sense.  Thanks for your time.

**Comment by nutti** [comment]
@LDAsh72 

Hi,

All you want to do about this feature is same as below links?
Below link shows that texel density is not changed when meshes are scaled.

http://www.3dtotal.com/tutorial/1813-texel-density-for-game-art-3ds-max-unreal-dev-kit-by-tim-diaz-udk-bricks-tutorial-environment?page=2

I did not understand about World Scale UV.
So I may write from scratch, and it may be faster than modification.

**Comment by LDAsh72** [comment]
This time I will provide some pics. :P

For a quick example, I started with a basic layout of planes, one set has X4 quads and the other has X64.

Now, imagine these aren't just a handful of quads that can be easily adjusted, but various "sectors" (averaging between quarter to half a million triangles each) of complex interior geometry for a level in a 3D game using modern polycounts, and we want to be able to bake lightmaps and paint texels into that lightmap after baking - without any seams.
This is important to think about, to avoid just concluding "why don't you just XYZ whatever..." (which I've heard from dorks before).  This is a simple demonstration.  In practice - things get a LOT more complicated.  So it's pointless for anyone to say "oh why don't you just...by hand", this really does need automation.

So I use "UV Unwrap" - "Lightmap Pack" - "Pack Quality '48'", then I "Pack Islands '0.1'" (for the small X4 set) and '0.00625' (for the large X64 set) (a 16th difference).  Whatever the unwrapping process, I do not want this changed later, but as you can see in this following pic, the size of the UVs are not proportional:-
http://www.violae.net/temp/UVworldscaleexample1.png

Next, I load the scene into 2.66a and use the "World Scale UV" addon, the _only_ way I know of getting these results - by getting around that Python error in this particular version of Blender with this particular addon (not the latest), so my UV layout is _not_ changed, by the scale of all of these quads, no matter if they are part of the same "object" or not - this is important, given the size and complexity of the geometry in practical cases, they can't be thrown together as 1 entire object.

The end result is that all "sectors"/objects (given that I begin to scale with the largest UV layout, and using that exact scaling on every other smaller/lesser sector/object throughout the level) can now have lightmaps baked and texels painted in and the size of those texels will match and everything will be consistent, and seams are mostly avoided:-
http://www.violae.net/temp/UVworldscaleexample2.png
http://www.violae.net/temp/UVworldscaleexample3.png

I hope that finally clears things up.  If not, I'm not sure what else I can say or show.

**Comment by nutti** [comment]
@LDAsh72 

Ah..., I may get your request.
Do you want same UV size when polygon's size is same?


> Next, I load the scene into 2.66a and use the "World Scale UV" addon, the only way I know of getting these results - by getting around that Python error in this particular version of Blender with this particular addon (not the latest), so my UV layout is not changed, by the scale of all of these quads, no matter if they are part of the same "object" or not - this is important, given the size and complexity of the geometry in practical cases, they can't be thrown together as 1 entire object.

And, I have a question about your error on 2.66a.
What is error about Python?
Maybe I can fix when you show me error message.

**Comment by nutti** [comment]
I remade this feature.
Please try this one from below link.

https://github.com/nutti/Magic-UV/archive/spike_wrap.zip

You can use World Scale UV by below procedure.

1. Select face whose scale will be measured.
2. Press **U** key.
3. Execute **World Scale UV** > **Measure**
4. Select face which will apply world scale UV.
5. Press **U** key.
6. Execute **World Scale UV** > **Apply**

Thanks.

**Comment by LDAsh72** [comment]
[quote]Ah..., I may get your request.
Do you want same UV size when polygon's size is same?[/quote]Sorry, I don't really understand this question.  How can the polygon size always be the same?  If you are talking about "actualising" the scales/rotations/etc. (CTRL+A), then I always do that before these operations, there's no need to mess around with that after the fact.  Unwrapping the lightmap and texture-paint channels is the final operation that would be executed.  No further tweaks.

[quote]And, I have a question about your error on 2.66a.
What is error about Python?
Maybe I can fix when you show me error message.[/quote]As for the original World Scale UV with 2.66a, on the "first click", here's how it happens...
I set up my 2nd UV channel "lightmap".  Uncheck "Force Unwrap".  Click "Set Material Size" (1.00 1.00).  Click the button:-
[code]Traceback (most recent call last):
  File "C:\Program Files\Blender\2.66a\2.66\scripts\addons\object_realsize_unwrap.py", line 326, in execute
    DoRealWorldUnwrap()
  File "C:\Program Files\Blender\2.66a\2.66\scripts\addons\object_realsize_unwrap.py", line 249, in DoRealWorldUnwrap
    scalefactor = GetObjectUVScaleFactor ( selectedObj )
  File "C:\Program Files\Blender\2.66a\2.66\scripts\addons\object_realsize_unwrap.py", line 189, in GetObjectUVScaleFactor
    faceScale = getFaceUVScale(obj, face) # attempt to get single face scale factor
  File "C:\Program Files\Blender\2.66a\2.66\scripts\addons\object_realsize_unwrap.py", line 137, in getFaceUVScale
    tCoords[ArrayIndex] = obj.data.uv_layers[UVMapName].data[Verts[ArrayIndex]].uv
KeyError: 'bpy_prop_collection[key]: key "UVMapWorldSize" not found'

location: <unknown location>:-1
[/code]
Then, without doing ANYTHING ELSE but simply clicking the button again, it works:-
[code]bpy.ops.object.editmode_toggle()
bpy.ops.mesh.select_all(action='SELECT')
bpy.ops.object.editmode_toggle()
bpy.ops.object.editmode_toggle()
bpy.ops.uv.select_all(action='SELECT')
bpy.ops.transform.resize(value=(95.911, 95.911, 95.911), constraint_axis=(False, False, False), constraint_orientation='GLOBAL', mirror=False, proportional='DISABLED', proportional_edit_falloff='SMOOTH', proportional_size=1, snap=False, snap_target='CLOSEST', snap_point=(0, 0, 0), snap_align=False, snap_normal=(0, 0, 0), texture_space=False, release_confirm=False)
bpy.ops.object.editmode_toggle()
[/code]

And this gives the desired results.

**Comment by schroef** [comment]
Does this feature really scale to world scale? I see a other tool from UV tool and when i use this in object mode the scale of the texture is different then using this feature

**Comment by nutti** [comment]
Magic UV now only supports to 2.77+  
If I support old Blender version, it will lose chance to make new feature.

So, I will close this issue.
