### ISSUE TITLE
using develop version, addon doesnt show?

### ISSUE THREAD

**Issue by schroef** [nutti/Magic-UV#45]
I wanted to try the develop version and dropped the uv_magic_uv folder manually in addon folder of blender. Addons shows in panel, it activates, but i dont see it show up. 

I see a "internal error" with the pack feature. Not sure how it exactly works. I made a plane duplicated it on X- & Y-axis. Unwrapped it and devided them in 2 groups/islands, then hit pack.

**Comment by nutti** [comment]
@schroef 

See below links.
You can learn how to use it.

https://github.com/nutti/Magic-UV/wiki/Tutorial#pack-uv

**Comment by schroef** [comment]
I did it like that and then I get that error in yellow text

**Comment by nutti** [comment]
@schroef 

Hi,

I updated develop branch.
Can you try it?

**Comment by schroef** [comment]
What the difference between your pack item and the basic blender pack item... i dont see any difference between the 2???

**Comment by nutti** [comment]
@schroef 

The tutorial video consists of two phase.

* First phase
  * This is **Pack Island** feature which blender has.
* Second phase - This is **Pack UV** feature which this add-on has
  * This feature merges same island when packing island. So, More UV space can be used.

**Comment by schroef** [comment]
Im doing exactly as in your video, but the pack uv does the same as pack island, it doesnt keep island together?? 

When show pack islands you see them spreaded out over the uv, then flip back to a position, i dont know what happens here???

Than you use pack uv and it packs them keep the packs together. When i try this they still keep being spread

**Comment by schroef** [comment]
okay, sorry... Ive tried it now for the about 5 times and now i got it to work like in the video. I now used align/distribute to get the island perfect and then do your pack uv's. It oonly works when they are perfect match on each other.

This seems only possible with perfect unwrapped meshes. Isnt it possible to have a sort of safety margin around the island?? or doesnt it work like that?

**Comment by nutti** [comment]
@schroef 

> It oonly works when they are perfect match on each other.

yes, current Version must match among islands.

> Isnt it possible to have a sort of safety margin around the island?? or doesnt it work like that?

I think yes.

**Comment by nutti** [comment]
@schroef 

I added option "Allowable center/size deviation".

https://github.com/nutti/Magic-UV/commit/fe3be9f3fc6947bd1435991f7ac82300b6598d76

So, I close this issue.
