### ISSUE TITLE
Improve packaging uv island by groups.

### ISSUE THREAD

**Issue by lpslp** [nutti/Magic-UV#47]
hi. Here video http://www.headus.com/au/doc/uvlayout-expert/videos/UVLayout-Packing-2.mov with example of what i mean. In two words - it would be nice to have possibility to group some uv island with others. And when it paking these groups placed near it parts.

**Comment by mifth** [comment]
Hi.

There will be new packing in blender. It's in WIP https://wiki.blender.org/index.php/User:SaphireS/gsoc2016/proposal

I would leave it for blender developers.

@nutty already did good packing extension which i use. https://github.com/nutti/Magic-UV/issues/41

**Comment by nutti** [comment]
@mifth 

Thanks for replying.

> There will be new packing in blender. 
> It's in WIP https://wiki.blender.org/index.php/User:SaphireS/gsoc2016/proposal

BTW, if this proposal implemented, #41 is still needed?
I'm afraid that it will be duplicated feature.

**Comment by mifth** [comment]
Dunno know.
I use your script )

**Comment by nutti** [comment]
OK, thanks.

**Comment by nutti** [comment]
@lpslp 

Does above discussion meet your request's requirement?

**Comment by nutti** [comment]
@lpslp 

If there is no comment about this issue, I will close on weekend.

**Comment by nutti** [comment]
I will close this issue because there is not any comment.
