### ISSUE TITLE
Copy set of UV and paste it to multiple selected faces at once

### ISSUE THREAD

**Issue by oxysoft** [nutti/Magic-UV#48]
This add-on has been very useful to me and has made my work a lot easier but there is something that would help even more. Take this small portion of this low poly stage I am working on right now

http://i.imgur.com/08onfLN.png

I want to add the floor texture to the faces I have selected but to do this, I'd have to copy the UVs of exactly 32 other faces with the floor UVs or copy one face and paste it 32 times to the faces that I want. 

I'd like to be able to simply copy the UVs of one floor face and be able to just paste it to all the selected faces all at once. Currently it'll tell you "Number of selected faces is different from copied (src:1, dest:32)"

Hope that made sense!

**Comment by nutti** [comment]
@oxysoft 

Hi, thanks for using this add-on.

This add-on has already this feature.
You can copy to multiple faces at once when you select **N:M** on **Strategy** option.

![n_m_paste](https://cloud.githubusercontent.com/assets/1463952/16078056/70c81140-3337-11e6-9a5c-1ff967444e47.png)

Here is the tutorial video.

[![](http://img.youtube.com/vi/YB2ykesaKi8/0.jpg)](https://www.youtube.com/watch?v=YB2ykesaKi8)

Thanks.

**Comment by oxysoft** [comment]
Works perfectly, thanks!
