### ISSUE TITLE
Shortcuts for copy/paste UVs do not work

### ISSUE THREAD

**Issue by oxysoft** [nutti/Magic-UV#49]
I tried setting shortcuts to copy and paste UVs to speed up my workflow (ctrl-shift-c and ctrl-shift-v respectively) but nothing happens when hitting these shortcuts whereas it should work just fine.

**Comment by nutti** [comment]
@oxysoft 

Hi,

What is your configuration?
I want to know your configuration to investigate.

**Comment by oxysoft** [comment]
Not sure exactly what you mean by configuration (kind of new to Blender altogether) but if you go into user preferences, export key configuration, add these entries then re-import

    kmi = km.keymap_items.new('uv.muv_cpuv_copy_uv', 'C', 'PRESS', shift=True, ctrl=True)
    kmi_props_setattr(kmi.properties, 'uv_map', 'UVMap')
    kmi = km.keymap_items.new('uv.muv_cpuv_paste_uv', 'V', 'PRESS', shift=True, ctrl=True)
    kmi_props_setattr(kmi.properties, 'uv_map', 'UVMap')

Shortcuts will not work despite being defined there

**Comment by nutti** [comment]
@oxysoft 

Thanks.

I have one more question.
Is there any message on Info Window?

**Comment by oxysoft** [comment]
Nope, nothing happens at all. It seems to do nothing with the defined shortcut from my understanding. If you do U > Copy/Paste UV > Copy UV > right click on [Default] > Add a shortcut and then set a shortcut from there, doing the same steps again should say "Change shortcut" instead of "Add a shortcut" but instead, it simply remains as "Add a shortcut" which means it's probably not setting it right or something like that

**Comment by mifth** [comment]
I guess you need to set some parameters to the copy/paste method.

`bpy.ops.uv.muv_cpuv_copy_uv(uv_map="")`

As you can see there is **uv_map** parameter.

**Comment by oxysoft** [comment]
That does not work unfortunately

**Comment by mifth** [comment]
I'll test when i get my computer.

**Comment by oxysoft** [comment]
any update on this?

**Comment by mifth** [comment]
Hi.
Sorry, i forgot to answer.
If you add the code like this - it will work:
`
bpy.ops.uv.muv_cpuv_copy_uv()  # CopyUV
bpy.ops.uv.muv_cpuv_paste_uv()  # PasteUV
`
Just create your own custom clas which will have this line to copy/paste.
For example you can copy like this:

`
kmi = km.keymap_items.new(my.own_class_copy', 'C', 'PRESS', shift=True, ctrl=True)
...
...
...

class MyClassCopy(bpy.types.Operator):
    bl_idname = "my.own_class"

    def execute(self, context):
        bpy.ops.uv.muv_cpuv_copy_uv()  # CopyUV

`

**Comment by oxysoft** [comment]
Still doesn't work for me

**Comment by mifth** [comment]
Well, it works in Blender Python console. It works. 
I guess you did something wrong.

**Comment by nutti** [comment]
@oxysoft, @mifth 

Sorry for slow reaction.
I tested shortcut key allocation for my script using @mifth 's script.
And it works correctly.

Please check below script.

https://gist.github.com/nutti/e9debe9973681e1fd21c6977c115cc61

**Comment by nutti** [comment]
@oxysoft 

any update about this issue?
If you don't have problem, I will close this issue.

**Comment by nutti** [comment]
I closed this issue.
