### ISSUE TITLE
Transfer UV is broken.

### ISSUE THREAD

**Issue by mifth** [nutti/Magic-UV#50]
Hi.

I found that you broke Transfer UV by this commit.
 https://github.com/nutti/Magic-UV/commit/bb6b8fe6a46d00063472837c25cc9a3cafb26336#diff-c31e70513a04ee2cb59053553d0598a1
 It it works wit errors now.
I see also you modified the code in many places of the Transfer UV. But what for? I already optimezed the code of the Transfer UV.

Could you revert your changes, please?

I added the file where it's not possible to paste uvs through Transfer UV.

[untitled.zip](https://github.com/nutti/Magic-UV/files/335393/untitled.zip)

**Comment by nutti** [comment]
@mifth 

Hi,
Thanks for your report.

Sorry, I failed to revise Transfer UV properly.
Then, I fixed this issue.

cae7bef

Please check fixed version from below link.

https://github.com/nutti/Magic-UV/archive/develop.zip

**Comment by mifth** [comment]
Hi.

Now it works fine! Thanks a lot!
