### ISSUE TITLE
UV Transfer is broken

### ISSUE THREAD

**Issue by mifth** [nutti/Magic-UV#51]
Hi.

UVTransfer is broken. Could you check it, please?

https://youtu.be/PuF2ougVoVE

[temp1.zip](https://github.com/nutti/Magic-UV/files/519603/temp1.zip)

**Comment by mifth** [comment]
Blender 2.78
Magic UV 4.0 from master

**Comment by mifth** [comment]
I tested develop branch. It's broken too.

**Comment by nutti** [comment]
@mifth 

Sorry for late response.

I have a question about your problem.

1. is there any problem when you use Blender whose version is  < 2.77
2. is there any problem when you use Magic UV whose version is < 3.2

**Comment by mifth** [comment]
Hi,
I have just tested Magic UV 3.2 with blender 2.78. It works ok.

Possibly, you did a mistake during refactoring.

**Comment by nutti** [comment]
@mifth 

Hi,

Thanks your testing.
I tested your blend file with your video too, but it works correctly in my environment.

**Comment by mifth** [comment]
Hello @nutty ,
Hm.. I cleared python cache then tested again.
With this blend file master branch works with issues but the develop branch works ok.
I'll be testing the development branch for a while now. I hope there is no an issue anymore in the develop branch.

Leave this issue for a week, please. I'll be using UV Transfer with the develop branch all the week. 
Thanks.

**Comment by nutti** [comment]
@mifth 

OK,  I will remain this issue.
If you have problem, please tell me.

**Comment by nutti** [comment]
Ah, I will release v4.1 soon because v4.0 is very old and has some bugs.
If this issue is closed, I will tackle to release v4.1.

**Comment by nutti** [comment]
@mifth 

I think you use v4.0 which does not fix this issue.
There is already same issue on #50 , and already fix this issue on develop branch.
However I have not released v4.1 yet.

Please check develop branch.

**Comment by mifth** [comment]
Hi,
I tested the uvtransfer at friday. All worked fine. I will be testing the plugin during next week. I think all is fine. It's good idea about 4.1 version.

I'm closing the issue. If there will be any problems i'll write here.

Thank you a lot for your time.
