### ISSUE TITLE
Addon draws empty panels

### ISSUE THREAD

**Issue by vilemnovak** [nutti/Magic-UV#52]
Hi, your addon draws empty panels in blender when not on. Please use a poll() function, to hide the panel when the functions are not on - it is now wasting unnecessary space. Also, when people allready install your addon, they probably expect the functions to be on, not off. I thought I just downloaded a disfunctional addon.

**Comment by mifth** [comment]
Hi, 
Could you give exact steps to get empty panels, please?
Also, where should be put the poll() function?

Thanks.

**Comment by mifth** [comment]
Or may be you would like to contribute? Just make a pull request into the development branch.

**Comment by vilemnovak** [comment]
it's easy:
https://www.blender.org/api/blender_python_api_2_78_release/bpy.types.Panel.html

if poll returns true ~ panel is drawn, false - not drawn ;)

**Comment by mifth** [comment]
Then make the pull request. It's easy too. :)

**Comment by nutti** [comment]
@mifth 

Hi,

I think @vilemnovak points out to hide below Panel when their feature is off.

![github_20170112](https://cloud.githubusercontent.com/assets/1463952/21887014/85347108-d901-11e6-816b-854beaaee657.png)

@vilemnovak 

I already know ```poll()``` function to hide them, but I did not have a time to fix it.  
I'm going to fix them in next release. But I will add you as author if you fix and pull request to develop branch, and I'm very happy to save my time :-)

**Comment by vilemnovak** [comment]
thanks for the offer, I allready contribute to far too many projects :)

**Comment by nutti** [comment]
Improve UI from commit 703f5fad387aa46d286dc3f981be0576c0cb8080

Check it above commit

**Comment by nutti** [comment]
@vilemnovak 

This revision is now on develop branch.  
Can you try this one?

https://github.com/nutti/Magic-UV/archive/develop.zip

**Comment by nutti** [comment]
@vilemnovak 

Is there any problem?  
I will close if there is no problem about newest (on develop branch) version on next week.
