### ISSUE TITLE
wiki: Transfer UV needs exactly 2 faces

### ISSUE THREAD

**Issue by capnm** [nutti/Magic-UV#53]
Hi nutti, if I understand the function correctly, the Transfer UV description
in the wiki-tutorial isn't correct:

Select face which UV will be copied
 **(You can select more than two faces)**
Press key U
Click Transfer UV > Transfer UV Copy
Select face which UV will be pasted
**(You MUST select same number of face to be copied)**

I think it should be something like:

Select **2 adjacent faces** to determine the direction of the UV-mapping that will be copied.
Press key U, Click Transfer UV > Transfer UV Copy

In an another mesh, that have the same count of visible faces, select 2 adjacent faces
to specify the direction of the pasted UV-mapping.
Press key U, Click Transfer UV > Transfer UV Paste

In both meshes you can hide (Key H) all faces where the UV-mappings should not be altered.
If you leave in the destination mesh multiple isles (with the same count of faces) unhidden and 2 faces selected, the UV-mapping will be transferred to each isle. 

Thanks

**Comment by nutti** [comment]
Thanks for your great tutorial.
I think it was old tutorial.

merged your tutorial to wiki page.

https://github.com/nutti/Magic-UV/wiki/Tutorial#transfer-uv

Thank you!!

**Comment by capnm** [comment]
Thanks, it's a very useful add-on :-)
