### ISSUE TITLE
Copying marked seams

### ISSUE THREAD

**Issue by fmb501** [nutti/Magic-UV#54]
I can get the uv coordinates to copy, but there are no seam markings in the object I past the UV to.  This makes it difficult to make changes to those objects to which uv's have been copied.

Is there a way to capture the seam markings from the original un-wrapped master to the copies?  

It seems logical that Blender stores that information somewhere, but perhaps it can't be retrieved and applied to the new objects.

I'd be happy with just copy / past or transfer the seam markings and then create the UV coordinates my unwrappeing the model.

I see this has been requested by others, but I haven't seen a definitive response as to why transferring seam markings isn't feasible.

**Comment by mifth** [comment]
Me and @nutti  had an idea to add seams copying. But it takes some additional work.

Btw, we could add any data copying. Not only UVS. Point Colors, point Weights, edge Creases, face Material etc.

But it takes time...

**Comment by fmb501** [comment]
Thanks for the prompt reply.  The ability to copy / transfer all seams would be really useful.  I’ve seen at least a dozen other questions about copying seams on other forums so I think once the word is out that it can be done, I think a lot of people will want to use it.

Just let BlenderNation and Blender Artists know it’s available and watch people start flocking to your GitHub.

Other materials and data would be good as well, but what I’ve been waiting for is a way to save nodes as a separate file and name that could be appended to a projects.  I’m not talking about appending from a blend file.

I would like to create a custom node group such as “Snow” and be able to save it to a file called Snow.node so I wouldn’t have to remember which blend it was in or create a separate blend for it.  All of the *.node files would be my go to favorite nodes to quickly add to my project.

It probably can’t be done or someone would have created that addon by now.

Blender Sense’s Alchemy addon comes close but it has problem with speed and memory.  I’ve had to start my liberary over a couple of times now, which is time consuming.

Thanks again,
Fred

**Comment by nutti** [comment]
@fmb501 

hi,

thanks for your report about this add-on.
i will add your request to my ideas, but it takes long time because i'm busy now.

> Other materials and data would be good as well, but what I’ve been waiting for is a way to save nodes as a separate file and name that could be appended to a projects. I’m not talking about appending from a blend file.

btw, what is this request?
is this related to UV?

**Comment by fmb501** [comment]
Actually, my request was to be able to transfer /copy UV seams from one object to an identical object.  Transferring / copying UV coordinates is helpful, but if I want to make individual changes to the geometry of the objects without seams, it’s difficult to tell where those seams were on the master object.

I don’t care as much about the UV coordinates if I can copy the seams because when I unwrap everything, as long as the seams are there, UV coordinates will be generated.

Hope this better defines my request.

Everything else I mentioned was nice to have sometime in the future.

Regards
Fred

**Comment by schroef** [comment]
You can add the seams when they are copied in the UV editor. In the UV editor>Seams>Seams from islands. This way you have seems when the UV are copied. Perhaps some options settings would be nice to automate this, like a preset orso

**Comment by fmb501** [comment]
Thanks, I didn’t know that.

However, going through every object and adding the seams can be tedious if there are many duplicates of the original master.  Maybe there is a way around that was well, but there is a lot of functions in Blender that the casual artist like me never stumble across.

Thanks again.

**Comment by schroef** [comment]
Yes, thats why my proposal is for some settings to that add "seams from islands" by default.

**Comment by nutti** [comment]
@fmb501 

hi,

i made a prototype for adding copy/paste marked seams option.
can you check and it works correctly.

![github_20170718](https://user-images.githubusercontent.com/1463952/28316681-bfc56a30-6bfe-11e7-9527-1a9d202eceb0.png)

and..., this is a prototype version, so this option is only available to **Copy/Paste UV**.
if there is no problem, i will also add this option to the other features.

Thanks.

**Comment by nutti** [comment]
@fmb501 

oh, sorry.
this prototype is in develop branch.

https://github.com/nutti/Magic-UV/archive/develop.zip

**Comment by nutti** [comment]
@fmb501 

hi, i added copy/paste seams option to all features.
and is already in develop branch.

https://github.com/nutti/Magic-UV/archive/develop.zip

if you have problem, i will close this issue.

**Comment by mifth** [comment]
Hi!

I have just tried the develop brunch. I cannot transfer seams.

![selection_156](https://user-images.githubusercontent.com/2251298/28718652-8f3be2fa-73af-11e7-85a0-a430b4994b59.png)
[temp1.blend.zip](https://github.com/nutti/Magic-UV/files/1183128/temp1.blend.zip)

**Comment by nutti** [comment]
@mifth 

thanks,
now i fixed this problem, and can be downloaded the fixed version from develop branch.

plz check it.

**Comment by mifth** [comment]
Ok, I updated the code. Still cannot copy seams.

[Kazam_screencast_00011.mp4.zip](https://github.com/nutti/Magic-UV/files/1183394/Kazam_screencast_00011.mp4.zip)

**Comment by mifth** [comment]
OOoooh!! It seems I was not at Develop branch. Sorry. 
I updated the Develop branch and it work great now! 
I tested Copy UVS and Transfer UVs.

**Comment by nutti** [comment]
no problem.
if you have any other problem, plz tell me.

will close this issue in next week.

**Comment by nutti** [comment]
released version 4.4 and committed to Blender's official repos.
so, close this issue.
