### ISSUE TITLE
World Scale UV

### ISSUE THREAD

**Issue by nafergo** [nutti/Magic-UV#55]
World Scale UV seems that is not working. Tried to replicate your World Scale demo/tutorial but nothing happens. Menu options are there but nothing happens. No error also... Not sure if I'm doing something wrong...

Using 2.78 from 2017-06-13 (builder.blender) on Ubuntu 16.04 64bits.

**Comment by nafergo** [comment]
After installing http://www.mindonwaves.com/misc/blender-addon-archi-uv/ the World Scale UV measure/apply works as expected...

**Comment by nutti** [comment]
Hi,

Can you tell me more detail about your problem with your process?

this add-on does not depend on Archi-UV.
so, i did not understand why World Scale UV works correctly after installing Archi-UV

**Comment by nafergo** [comment]
Couldn't replicate on another computer (same OS and blender version), so installing Archi-Uv doesn't solve.
1- Added plane
2- Assigned material with image texture
3 - duplicated plane, rescaled and applied scale (so I get different planes with different dimensions but both with scale 1)
4- Edit mode on plane2, Measure
5- Edit mode on plane 1, Apply
nothing happens... 
- tried with different materials on different planes (same texture but different material name)
- tried measure on plane 1 and apply on plane2
- tried with cubes instead of planes

**Comment by nutti** [comment]
thanks.

btw, did each plane have more than one UV map?

if you have no UV map, error will occur as below.

```
Object must have more than one UV map
```

**Comment by nafergo** [comment]
I had 1 UVmap but I also tried with two UVmaps in each plane. No luck.

**Comment by nutti** [comment]
Hi, i fixed this problem.

you can try to the fixed version from devleop branch

https://github.com/nutti/Magic-UV/archive/develop.zip

can you try this one, please?

**Comment by nutti** [comment]
@nafergo 

is there any problem about the fixed version?

if there is no issues, i will close

**Comment by nutti** [comment]
there is no reaction about this issue.
so i will close.

reopen this issue or make new issue if there is problem.
