### ISSUE TITLE
New Feature: UVW Map

### ISSUE THREAD

**Issue by nutti** [nutti/Magic-UV#58]
Feature Merge Request by Legofon.
https://blenderartists.org/forum/showthread.php?391573-Add-on-Magic-UV-v4-3-(Copy-Paste-UV-Preserve-UVs-UV-Bounding-Box-and-so-on)&p=3201833&viewfull=1#post3201833

UVW Map is an add-on whose author is hp9000.
He agreed to integrate his add-on to Magic UV.

However, his script is old and must be refactored (ex. use bmesh ...).
And, his script is applied no license, so I will apply GPL to his script.

Newest version is in D.B.O (https://developer.blender.org/F20698)

**Comment by schroef** [comment]
It's a great addon, still works great. What will the difference be then with better B-mesh support?

**Comment by nutti** [comment]
i think there is no difference between B-mesh and original one.
however, the original script targets to Blender v2.6x.
so we must rewrite it with the better way.

**Comment by nutti** [comment]
Added this feature to the develop branch

**Comment by nutti** [comment]
you can use this feature from **U** > **UVW**

<img width="576" alt="uvw" src="https://user-images.githubusercontent.com/1463952/29250092-21f9f3ec-8077-11e7-91a7-5c7ac7c19066.png">
