### ISSUE TITLE
Preserve UV Aspect not working in Blender 2.78c

### ISSUE THREAD

**Issue by Copperplate** [nutti/Magic-UV#61]
Hi Nutti,

Thank you for your continued development of this amazing addon. I thought I should let you know that the Preserve UV Aspect feature is no longer working in Blender 2.78c. An error message occurs up to version 4.3 of the addon, but in the latest versions (4.4, 4.5) the error no longer shows, but the Preserve UV Aspect operation still does not work. I have attached a screenshot of the error (visible in 4.3). Thanks so much for your time and excellent work!
-Adam

![preserveuvaspecterror](https://user-images.githubusercontent.com/16230743/29253493-21b62bfe-8044-11e7-8276-4a384cc26120.PNG)

**Comment by nutti** [comment]
@Copperplate 

I checked this feature on 2.77c and 2.78c, and I confirmed it works correctly in my environment.
can you tell me your process?
if you have any .blend file which I could reproduce this issue, please send me.

**Comment by Copperplate** [comment]
Hi Nutti, thanks so much for checking this and sorry for the late reply. I just finished doing some more testing with version 4.4 and it appears the operation does not work as expected when Blender is set to Cycles Render, however, it works correctly in Blender Render.

In the attached project:

1. In Blender Render, I have the "Square" image assigned (in the UV Editor) and want to preserve its aspect in the "Non-Square" image.

2. I select U > Preserve UV Aspect > "Non-Square". The "Non-Square" image is automatically assigned. Everything works correctly, except the UVs shift over a bit to the RIGHT, and do not stay centered.

3. Ctrl-Z to undo.

4.  In Blender Render, I have the "Non-Square" image assigned and want to preserve its aspect in the "Square" image.

 5. I select U > Preserve UV Aspect > "Square". The "Square" image is automatically assigned. Everything works correctly, except the UVs shift over a bit to the LEFT, and do not stay centered.

6. Ctrl-Z to undo.

7. I switch to Cycles Render, and select Use Nodes in the Material's Surface Properties.

8. In Cycles Render, I have the "Square" image assigned (in the UV Editor) and want to preserve its aspect in the "Non-Square" image.

9. I select U > Preserve UV Aspect > "Non-Square".  The "Non-Square" image is not assigned. However, the UVs update, and if you manually switch to the "Non-Square" image in the UV Editor, it looks correct (but is shifted RIGHT).

10. Ctrl-Z to undo.

11.  In Cycles Render, I have the "Non-Square" image assigned and want to preserve its aspect in the "Square" image.

12.  I select U > Preserve UV Aspect > "Square". The "Square" image is not assigned. The UVs also do not update.

13. However, if I select U > Preserve UV Aspect > "Non-Square" while the "Non-Square" Image is still assigned, the UVs unexpectedly receive the "Square" image's aspect.

Thanks so much for your time and effort. I hope this info helps a bit. Please let me know if you have any other questions.

-Adam
[PreserveUV_TEST.zip](https://github.com/nutti/Magic-UV/files/1222906/PreserveUV_TEST.zip)

**Comment by Copperplate** [comment]
Hi, Nutti, thank you once again for this great plugin... I have been switching to Blender Render temporarily when I need to Preserve UV Aspect and it works great.

I've also been using it quite a bit today to copy and paste UVs into my Texture Atlas. The built-in Texture Atlas add-on in Blender unfortunately did not work reliably "as-is" because some faces were unassigned in certain UV maps but assigned in others. This seemed to confuse it.

**Thankfully, your MagicUV addon allows me to work around this** by manually pasting my UV Maps into another UV Atlas. :1st_place_medal: Of course it also allows me to preserve the UV aspect of non-square images when transferring the UVs into the Atlas.

This caused me to wonder if it would be at all possible to create a "Make Texture Atlas" option, which would combine all UV maps in an object into a new UV map and preserve the aspect ratio of the original UVs. That last step (preserving the aspect ratio) is impossible for the current built-in Texture Atlas Add-on, and as mentioned, for some reason it also struggles with knowing whether to give assigned or un-assigned status to faces when the same faces have both status applied to them across multiple UV maps.

Of course, your addon is amazing as it is... this option would just simplify the number of steps needed to create an Atlas out of UV maps with different aspect ratios. :1st_place_medal: :)

Thanks so much for your consideration, and I totally understand if you see this as a unfeasible or unneeded feature.

Have a great rest of the week!

-Adam

**Comment by Copperplate** [comment]
UPDATE: I thank God for showing me a relatively simple way of converting non-square tileable textures into square tileable versions. This will save me a lot of hassle with textures in the future. Thankfully, your Preserve UV Aspect feature really helped out to salvage what I had already made... whew! :-)

So basically, please don't stress yourself about trying to add a "Make Texture Atlas" option. The only neat feature I could see would be to have MagicUV automatically do the math to preserve the UV islands' relative position after running "Preserve UV Aspect".

Thanks so much, Nutti, for your time. I hope I did not offend you in any way with my previous feature suggestions, my apologies if I did. Your plug-in has been a wonderful benefit to me as I learn game development and make assets for my game. :1st_place_medal: 

-Adam

**Comment by nutti** [comment]
@Copperplate 

sorry, i was busy and could not reply.
i have questions about your issue and clarify it.

> I just finished doing some more testing with version 4.4 and it appears the operation does not work as expected when Blender is set to Cycles Render, however, it works correctly in Blender Render.

was this problem already solved?

> This caused me to wonder if it would be at all possible to create a "Make Texture Atlas" option, which would combine all UV maps in an object into a new UV map and preserve the aspect ratio of the original UVs. 

Is this your feature request?


Thank you

**Comment by Copperplate** [comment]
Hi Nutti, thanks for your reply. No, the problem still exists as demonstrated in the .blend file in my earlier post (PreserveUV_Test.zip). Nevertheless, because I have now switched everything to square textures, I no longer have to worry about preserving aspect ratios at the present. However, whenever I needed to preserve the UV aspect, I would just switch to Blender Render temporarily and then back to Cycles after I was finished using Magic UV. That is a fairly easy workaround, so it's not a big issue.

As for the "Make Texture Atlas" option: originally I thought this would be a good idea, and maybe it still would be; however, **it's just so much simpler to keep all textures square,** and as long as one is able to do this, it is not important to have a Make Texture Atlas option that preserves the UV aspect.

However, one "feature request" that would be an improvement to an already great feature would be to  have MagicUV preserve the UV islands' relative position after running "Preserve UV Aspect". Currently if you run "Preserve UV Aspect", the new UVs will shift left or right (as demonstrated in the attached .blend above).

Please let me know if you have any other questions. Thanks for your hard work... I have used the Copy and Paste UV feature extensively over the past week... it's been great! :1st_place_medal: 

-Adam

**Comment by nutti** [comment]
@Copperplate 

Hi,

> However, one "feature request" that would be an improvement to an already great feature would be to have MagicUV preserve the UV islands' relative position after running "Preserve UV Aspect". Currently if you run "Preserve UV Aspect", the new UVs will shift left or right (as demonstrated in the attached .blend above).

ah, i may get your feature request.
i made a simple example about your request.

![feature_request_20170821](https://user-images.githubusercontent.com/1463952/29522584-a9dd00da-86c4-11e7-8ce7-8818cd26064e.png)

is my understanding along to your intention?

Thanks

**Comment by Copperplate** [comment]
Hi Nutti, yes, that's exactly what I think would be a great feature! Thanks so much for your effort in developing MagicUV. :-)

**Comment by nutti** [comment]
@Copperplate 

Hi, i added new option to select aspect origin.
but, it will work as you expected with default configuration.

![preserve_uv_aspect_improve_20170822](https://user-images.githubusercontent.com/1463952/29565851-a3357c26-8782-11e7-874e-befd06acd0a3.png)

you can try this one from develop branch.
could you try this one?

https://github.com/nutti/Magic-UV/archive/develop.zip

hope you like

**Comment by Copperplate** [comment]
Hey, Nutti, that sounds fantastic!! I will be busy for several hours today rendering and uploading video, but I will try out the new version as soon as I am able, and let you know how it goes. Thanks so much for adding that new feature!! :-)

**Comment by Copperplate** [comment]
Hi Nutti, I just tried out the new version of Magic UV... it's perfect and works great!!!  The "Center" option does exactly what I had imagined. Thank you so much for this amazing gift! :1st_place_medal:

**Comment by nutti** [comment]
@Copperplate 

Thank you for checking patch.
And then, i will close this issue.

if you have any problem, please reopen this issue or make new issue.

Thank you
