### ISSUE TITLE
UV Copy stop working [Bl2.79.1]

### ISSUE THREAD

**Issue by DOORAK** [nutti/Magic-UV#62]
Can be repeated [on this](http://www.gamedev.ru/files/?id=127735) simple scene (stupid 3 poly spheres)

1.Select Unwraped sphere [Earth]
2.CopyUV 
3.Select sphere withoun UV [Moon]
4. Create UV by +button in meshdata section or by any other way  
5. PasteUV
-=>>Boom!<<=-

Console log:

> --------------------------------------------
> bpy.ops.object.muv_cpuv_obj_copy_uv(uv_map="UVMap")
> --------------------------------------------
> Copy UV coordinate per object (UV map:UVMap)
> --------------------------------------------
> Earth's UV coordinates are copied
> --------------------------------------------
> bpy.ops.object.editmode_toggle()
> --------------------------------------------
> Paste UV coordinate per object (UV map: UVMap)
> --------------------------------------------
> Traceback (most recent call last):
>   File "/home/username/blender-svn/build/bin/2.79/scripts/addons/uv_magic_uv/muv_cpuv_ops.py", line 40, in __memorize_view_3d_mode
>     result = fn(self, context)
>   File "/home/username/blender-svn/build/bin/2.79/scripts/addons/uv_magic_uv/muv_cpuv_ops.py", line 463, in execute
>     l.edge.seam = ss
> SystemError: error return without exception set
> 
> location: <unknown location>:-1

**Comment by nutti** [comment]
@DOORAK 

Hi,

I fixed the bug you reported.
It's in bl2.79 and develop branch, and I will merge this patch to blender's official repos.

* Based on blender's official repos (it will be merged to blender's official repos)
  * https://github.com/nutti/Magic-UV/archive/bl2.79.zip
* Unstable branch (develop)
  * https://github.com/nutti/Magic-UV/archive/develop.zip

Thank you

**Comment by nutti** [comment]
merged to Blender's repos.
so I closed this issue.

https://developer.blender.org/rBA6aa1c9aeb6f412aced380cb78e912264defbd209
