### ISSUE TITLE
Box mapping fails at bevel

### ISSUE THREAD

**Issue by tuomammela** [nutti/Magic-UV#63]
I'm using unstable version 4.5. Box mapping seems to work great, but it fails with bevels. In my test case, horizontal bevel looks fine, but vertical is strange.

![image](https://user-images.githubusercontent.com/18626157/30510085-83eaa088-9ac6-11e7-97a8-8aa7d1eb5a5c.png)

![image](https://user-images.githubusercontent.com/18626157/30510090-94493bf6-9ac6-11e7-92bf-71e8fb5a822b.png)

Steps to reproduce:
1. create a cube
2. create a window hole, all 90 degree angles
3. add bevel to the four edges of the window hole
4. box map with magic uv

For some reason, appearance of this bug is inconsistent. Sometimes I need to add a wall and a bevel to the other side of the window hole too, and then the bug appears.

**Comment by nutti** [comment]
Hi,

sorry for my late response.
I could not check this problem temporarily for my current circumstance.

will answer when my circumstance becomes normal.

Thanks.

**Comment by nutti** [comment]
@tuomammela 

Hi,

can you send me .blend file which reproduces the issue?
from my environment, it seems to work correctly.

thanks.

**Comment by nutti** [comment]
@tuomammela 

can you respond this?
If there are no response in next week, i will close this issue.

**Comment by tuomammela** [comment]
Here you go:

[box map fail.zip](https://github.com/nutti/Magic-UV/files/1463569/box.map.fail.zip)

**Comment by nutti** [comment]
thank you.

i'll check it.

**Comment by nutti** [comment]
@tuomammela 

Thanks to your .bland file.
I could solve this issue.

Please check revised version from below link.

https://github.com/nutti/Magic-UV/archive/develop.zip

**Comment by tuomammela** [comment]
Well my quick test indicates that the problem seems to be gone. Great job!

**Comment by nutti** [comment]
thanks.
i will close this issue.

if you will have any new issues, please open new issue again.
