### ISSUE TITLE
Error while clicking 'Apply' for 'World Scale UV' Function 

### ISSUE THREAD

**Issue by jantma2** [nutti/Magic-UV#64]
After taking a 'Measure' on another UV map the function of 'World Scale UV' application failes with this message:
![error](https://user-images.githubusercontent.com/32648222/31349922-69711400-ad25-11e7-8c02-248bc774ff94.jpg)

This is the sample blend file:
[Test.zip](https://github.com/nutti/Magic-UV/files/1369321/Test.zip)

This is the texture that should be projected and scaled:
![0004-porcelain-floor-tiles-texture-seamless-hr](https://user-images.githubusercontent.com/32648222/31349980-a880228a-ad25-11e7-82ef-78aa9ff62ba6.jpg)

**Comment by nutti** [comment]
@jantma2 

Thanks, for your report.
This problem is already reported on Blender Artists.

Unfortunately, I couldn't solve this issue yet.
But your .blend file helps me a lot, so I can investigate the problem now.

**Comment by jantma2** [comment]
Does the blend file really show issue on your system? 
Some more tests make me think that the issue may rely on working with dimensions (mm preset) in blender. Starting a completly new virgin project using blender's basic setup make your plugin working.
Another guess from my side is a strange incompatibility with 'lux render' plugin.

**Comment by nutti** [comment]
yes, i can reproduce this issue with your .blend file.
i'm very happy to get the survey material.

**Comment by nutti** [comment]
@jantma2 

Thanks to your .blend file, i can solve this issue!
Fixed version can be available on below link

can you try it?

https://github.com/nutti/Magic-UV/archive/fix_64.zip

**Comment by jantma2** [comment]
Thanks for your quick support. The new verison seems to work.
