### ISSUE TITLE
UVM 5.0 Still see warning from MUVprops in console

### ISSUE THREAD

**Issue by schroef** [nutti/Magic-UV#68]
UVM 5.0
OSX 10.11.6
BL 2.78c

I still see those errors in the consule due to ALign Cursor
<img width="1090" alt="screen shot 2017-12-20 at 20 46 42" src="https://user-images.githubusercontent.com/6923008/34235427-0f500a7c-e5c8-11e7-986c-9f53302ebe35.png">

**Comment by nutti** [comment]
@schroef 

sorry, I forgot fixing this issue.
now I fixed this.
please try to check this one.

https://github.com/nutti/Magic-UV/archive/develop.zip

**Comment by schroef** [comment]
IT didnt happen all of the time, that was weird part. Ill try this version

**Comment by nutti** [comment]
Thanks. this issue may be solve, so I will closed it
