### ISSUE TITLE
Enhance Feature Transfer UV: Copy/Paste between meshes

### ISSUE THREAD

**Issue by nutti** [nutti/Magic-UV#70]
https://blenderartists.org/forum/showthread.php?391573-Add-on-Magic-UV-v4-5&p=3261353&viewfull=1#post3261353

> I though that the tools was to copy and paste Uvs between meshes with similar topology (objects duplicated), and didn't care if the meshes are part of same object or not.

**Comment by mifth** [comment]
hi. I tested the blend file which was attached. All works fine.
![image](https://user-images.githubusercontent.com/2251298/34501769-78337f70-f021-11e7-9b45-391a13b10922.png)

I used it like this.
COPY:
![image](https://user-images.githubusercontent.com/2251298/34501797-8e2c7818-f021-11e7-98cd-e2f765499f12.png)
![image](https://user-images.githubusercontent.com/2251298/34501811-99c9baf0-f021-11e7-8aef-5fe1f29a0234.png)

**Comment by nutti** [comment]
@mifth 

Thanks for your checking.
Maybe, this is the usage problem.
If the issuer solves this problem, I will close this issue.

**Comment by schroef** [comment]
I did check that scene way earlier. Was a different version of Magic UV. I also got that error, it would only work if the mesh had the same direction some how. 

If i would rotate it 180deg on Z it would transfer the uv properly.

I see there is a invert option now. Also wondering why the short cut has been taken out. Pressing 'U' now brings back the standard UV menu, nothing from Magic UV is there anymore. Is that correct?

**Comment by nutti** [comment]
> Also wondering why the short cut has been taken out. Pressing 'U' now brings back the standard UV menu, nothing from Magic UV is there anymore. Is that correct?

As I mentioned in BA, I deleted them because I think U menu should not be complicated.

**Comment by nutti** [comment]
No response from the reporter DcVertice.

**Comment by schroef** [comment]
Is this now working when mesh is flipped or rotated compared to the original mesh?
