### ISSUE TITLE
Handle UV island

### ISSUE THREAD

**Issue by nutti** [nutti/Magic-UV#73]
recognize UV island in features as below

* Align UV Cursor
* UV Bounding Box

**Comment by schroef** [comment]
Is this the CUrsor alignment which was added earlier, guess so. I only see center cursor now

**Comment by nutti** [comment]
I think current option "UV Island" is incorrect in Align UV Cursor.
It will make sense to change UV Island to UV.

**Comment by nutti** [comment]
Update features.
