### ISSUE TITLE
Why are older version released again?

### ISSUE THREAD

**Issue by schroef** [nutti/Magic-UV#78]
Im seeing tons of updates here and im wondering why older version are released again? Isnt that a lot of extra work your doing

**Comment by schroef** [comment]
Also in the readme.md we see now v5.0 as stable, but there is no valid link for this. When you check releases page last is still v4.5

See v5.0 as being a stable one
![screen shot 2018-02-13 at 12 08 55 pm](https://user-
images.githubusercontent.com/6923008/36160099-bf2d768c-10b6-11e8-89ba-f27f8da15d74.png)

The link is 404
![screen shot 2018-02-13 at 12 09 35 pm](https://user-images.githubusercontent.com/6923008/36160134-d28e0070-10b6-11e8-8ef8-356a14f945f5.png)

**Comment by nutti** [comment]
I didn't get your question.
I did not release any version now.

v5.0 will be released soon, please wait.

**Comment by schroef** [comment]
Well the new readme file shows version 5.0 yet the links is a 404. See the screen grab.

My initial question was all the updates to old files. I had like 10 updates in all kind of different versions. Perhaps during tags?

**Comment by mifth** [comment]
I got emails about all releases too. )
May be github bug.

**Comment by nutti** [comment]
I reattached the tag to the released commit.
Perhaps it may causes the lots of release notification. sorry

**Comment by schroef** [comment]
DId perhaps add all the zips perhaps in the release section?

**Comment by nutti** [comment]
No, i didn't touch except for the tags.

**Comment by nutti** [comment]
Ah, I think no need to revise README.md.
Because I will release v5.0 tomorrow at the earliest.
I added v5.0 link intentionally in advance.

**Comment by schroef** [comment]
ah okay, clear now

**Comment by nutti** [comment]
v5.0 released. this issue now is over

**Comment by nutti** [comment]
I have noticed that newly attached tags are not good condition.
I am going to reattach these tags tomorrow, so maybe lots of notification will send you from my experience.

Sorry for inconvenience.

**Comment by schroef** [comment]
Whats wrong with the tags than, could you enlighten?

**Comment by nutti** [comment]
If I see the tag, the revision pointed by the tag is incorrect.
I cound not understand why this is occurred.

But I find the solution in local test to fix this problem.
The solution needs to reattach all the tags I have already attached.

**Comment by schroef** [comment]
Not sure i get it, if i hover over a tag, in the bottom left corner i see proper tag.

![screen shot 2018-02-16 at 10 48 45 am](https://user-images.githubusercontent.com/6923008/36313154-17efdb00-1307-11e8-8693-9ab8a0325089.png)

When clicking it goes to that tag. Hovering over the source also shows proper zip.

I think i dont get it:)

**Comment by nutti** [comment]
Yes, source codes are no problem.
But commit history is not correct.
This is because there are two branches in parallel, so I must reattach tag to merged commit.

**Comment by nutti** [comment]
OK, I finished reattaching tags.
For now, it is good condition
