### ISSUE TITLE
World Scale UV Error when measuring / useability for fast 1m mapping

### ISSUE THREAD

**Issue by jcaonr** [nutti/Magic-UV#81]
If my screen layout in blender shows uv editor and 3d viewport side by side magic uv gives an error and can't measure the density. 

> Traceback (most recent call last):
>   File "\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\uv_magic_uv\ui\uvedit_editor_enhance.py", line 105, in draw
>     if sc.muv_uvcloc_enabled:
> AttributeError: 'Scene' object has no attribute 'muv_uvcloc_enabled'
> 
> location: <unknown location>:-1

----------
My use case: 
I need a 1mx1m mapping for the objects to export to a game engine. 
Would it be possible to add an option to set density by number? Just type in the measure?
 
Till now i was going to add a plane for every project (1mx1m) unwrap and measure it. Then apply to all my objects. Version 5 now also wants a texture added to the measured object and its hidden in the interface, so you need many more klicks to get the 1m x1m measure.

**Comment by nutti** [comment]
> If my screen layout in blender shows uv editor and 3d viewport side by side magic uv gives an error and can't measure the density.

Same as #79 
For now, can you use the unstable version instead.
Sorry for inconvenience.


> I need a 1mx1m mapping for the objects to export to a game engine.
> Would it be possible to add an option to set density by number? Just type in the measure?

Yes, you can do it.
Please change the **Mode** option to **User**, and you can change the target density as you like.
Does this meet your requirement?
If you have any trouble, please tell me.

**Comment by jcaonr** [comment]
Didn't mention this option. Meets the requirement pretty well. 

Thx for the fast reply and the great plugin!

**Comment by nutti** [comment]
Thanks.

If you have any problems about this add-on, please feel free to create the issue again.

For now, I will close.
