### ISSUE TITLE
Expected Behavior in Pack UV (extension)

### ISSUE THREAD

**Issue by juliocargnin** [nutti/Magic-UV#84]
Hi Nutti! Thanks for this handful Addon!

My questions are:
It this feature supposes to work recognizing identical islands and them overlapping each other or the islands must be overlapping before hitting 'pack uv'?

![screen shot 2018-02-22 at 11 48 09 pm](https://user-images.githubusercontent.com/36735037/36542193-d71b1534-182b-11e8-8272-33a6656d5524.png)
Two identical Islands not overlapped.
![screen shot 2018-02-22 at 11 48 13 pm](https://user-images.githubusercontent.com/36735037/36542194-d77755ec-182b-11e8-9584-430247fa4804.png)
after hitting 'pack uv' it didn't overlap each other. Would be good if they could do it instead.

![screen shot 2018-02-22 at 11 48 25 pm](https://user-images.githubusercontent.com/36735037/36542286-23c19f84-182c-11e8-9367-e0d95958950d.png)
Now I've overlapped them manually.

![screen shot 2018-02-22 at 11 48 30 pm](https://user-images.githubusercontent.com/36735037/36542293-27ae8b02-182c-11e8-8779-78c5e8e936bc.png)
after hitting 'pack uv' the script has maintained them overlapped. So it succeeds in this case.

Is that the expected behavior? Would be possible to make the addon recognize identical islands and then overlap them automatically?

**Comment by nutti** [comment]
Thanks for your report.

It also looks strange for me. I will check it.
Perhaps it is related to the issue #80

**Comment by mifth** [comment]
Hi.
I think islands should be overlapped before Packing.
For example, we can have some different bolts for low poly baking.
Here is an example of the same low poly meshes. But they will have different uv space:
![image](https://user-images.githubusercontent.com/2251298/36591028-a33520e0-18a1-11e8-891d-30b2a010dcb9.png)

**Comment by nutti** [comment]
@juliocargnin 

Hi,
Sorry for my late response.

@mifth send you the advice.
Is your issue solved?

**Comment by nutti** [comment]
There is no response for a long time.
And this seems to be a issue of usage question.
So, I close this issue for now.

@juliocargnin 

If you still have issues about this feature.
Feel free to reopen this issue or open new issue.
