### ISSUE TITLE
[B] Bounding box shows an error (v5.1.0)

### ISSUE THREAD

**Issue by schroef** [nutti/Magic-UV#85]
v 5.1.0
OSX 10.13.1
Bl 2.78c

I was trying the lastest release and noticed some new features. I believe the bounding box has been in there for a while. But in Blender 2.78c it doesnt work and shows an error when activating it.

See attached image
![screen shot 2018-04-02 at 3 11 11 pm](https://user-images.githubusercontent.com/6923008/38211551-dccd5bc4-3688-11e8-9aee-a5fe8193337b.png)

**Comment by nutti** [comment]
Thanks for bug report.
I will fix it.

**Comment by nutti** [comment]
fixed now.

**Comment by schroef** [comment]
Sweet, will try
