### ISSUE TITLE
AddOn option to access MagicUV through U key

### ISSUE THREAD

**Issue by Vinc3r** [nutti/Magic-UV#86]
I've noticed that Magic UV in 3DView moves its buttons to the Tool shelf Panel, and removes access from U key. 

Is it possible to make an option giving the possibility to make some options back to the U key? 

I understand that moving to the Tool shelf allows better tweaks of some manipulations, but having some basic and default operations directly into U key could save a lot of clics I think.

**Comment by schroef** [comment]
I had made a not of this as well earlier, really hope this comes back. Im mainly shortcut driven which keeps GUI clean and fewer panels. This new method is opposite of that.

**Comment by nutti** [comment]
@Vinc3r @schroef 

Hmm, shortcut key U seems better for saving time.
OK, I will make option which adds shortcut key about Magic UV feature.

**Comment by nutti** [comment]
Hi,

I added option for adding built-in menu which enables you to access Magic UV feature from built-in menu such as U key in View3D.

You can enable this feature from the add-on preference.

<img width="636" alt="github_20180506" src="https://user-images.githubusercontent.com/1463952/39673038-fb1b1434-516f-11e8-8e55-c20d594559f6.png">

**Comment by schroef** [comment]
Nice one!

**Comment by schroef** [comment]
Perhaps add tab menu like i did in this addon. This will make the addon pref much smaller, also makes it easier to read and find specific settings.

![screen shot 2018-05-06 at 3 05 59 pm](https://user-images.githubusercontent.com/6923008/39676833-0281c3e8-513f-11e8-9c17-16bbe1d6cbfd.png)

**Comment by schroef** [comment]
Sorry for that, I made a new request now.

**Comment by nutti** [comment]
@schroef 

Thank you.
I will try to implement your request.

**Comment by Vinc3r** [comment]
Nice, thanks for adding this option!
