### ISSUE TITLE
[req] adding tab menu to prefer panel

### ISSUE THREAD

**Issue by schroef** [nutti/Magic-UV#88]
Perhaps add tab menu like i did in this addon. This will make the addon pref much smaller, also makes it easier to read and find specific settings.

![screen shot 2018-05-06 at 3 05 59 pm](https://user-images.githubusercontent.com/6923008/39676833-0281c3e8-513f-11e8-9c17-16bbe1d6cbfd.png)

**Comment by schroef** [comment]
Yes works perfect. Im just not sure if those boolean menu are useful, i find those hard to click always :)

I tend to use these, you can click the complete button. 
Menu open (boolean)
![screen shot 2018-05-11 at 6 13 34 pm](https://user-images.githubusercontent.com/6923008/39949173-2f81d354-5547-11e8-9bf9-9b1457cb9c39.png)

Menu closed (boolean)
![screen shot 2018-05-11 at 6 13 38 pm](https://user-images.githubusercontent.com/6923008/39949179-3f72f37e-5547-11e8-90d0-31bb56ede427.png)

Code looks like this for that
![screen shot 2018-05-11 at 6 16 39 pm](https://user-images.githubusercontent.com/6923008/39949213-82635250-5547-11e8-949a-3ce1ba608d73.png)

You can also use this variation perhaps.
Menu open (boolean)
![screen shot 2018-05-11 at 6 14 09 pm](https://user-images.githubusercontent.com/6923008/39949236-a35797e6-5547-11e8-882f-0c9b4ed32ed6.png)

Menu closed (boolean)
![screen shot 2018-05-11 at 6 14 09 pm](https://user-images.githubusercontent.com/6923008/39949242-a981b0f2-5547-11e8-87e5-1115ae536db9.png)

THat code looks like this
![screen shot 2018-05-11 at 6 17 43 pm](https://user-images.githubusercontent.com/6923008/39949252-bc84cb08-5547-11e8-903c-d23333149393.png)

**Comment by nutti** [comment]
@schroef 

I fixed the UI.
It is now in issue_88 branch. (I will merge this to develop branch when you have no problem.)

https://github.com/nutti/Magic-UV/archive/issue_88.zip

can you check it?

**Comment by schroef** [comment]
Looks good and works with no issues on my old machine (2.78c)

What do you think of it, is it to much those boolean menu's? It does make evrything nice and compact doesn it.

**Comment by nutti** [comment]
@schroef 

> What do you think of it, is it to much those boolean menu's? It does make evrything nice and compact doesn it.

Sorry, I didn't get your suggestion.
Can you show me a prototype or pull requests?
It is difficult to implement the UI if there is only text.

**Comment by schroef** [comment]
No, it is a question. What do you think of this setup?

**Comment by nutti** [comment]
@schroef 

I think it's good.
If you don't have any problems about this, I will merge to develop branch.
Do you have any issues?

**Comment by schroef** [comment]
Its working properly

**Comment by nutti** [comment]
Thanks for your testing.
It is already in develop branch.
