### ISSUE TITLE
Texture Lock error in object mode and start/stop issue

### ISSUE THREAD

**Issue by NO4ME** [nutti/Magic-UV#89]
Automaticly turn off texture lock when user return to object mode (and maybe remember if it was on or off last time) and manipulate more vertices (one after another) without clicking stop/start every time. 
![issues](https://user-images.githubusercontent.com/39378030/40185053-ff87cb4a-59f1-11e8-92ec-032c2bb7953a.png)

**Comment by nutti** [comment]
Thanks for moving the discussion to GitHub.
I will improve the workflow as you show in Blender Nation.

**Comment by nutti** [comment]
@NO4ME 

Hi,

I fixed the issue you reported. And I tried to make better UI about this feature.
You can try fixed version if you want.

https://github.com/nutti/Magic-UV/archive/issue_89.zip

can you try this one?

**Comment by nutti** [comment]
This fix is already in develop branch.
You can try it from develop version now.

https://github.com/nutti/Magic-UV/archive/develop.zip

If you have any problem, feel free to reopen this issue.

**Comment by NO4ME** [comment]
Thank you for fixing issue in object mode but there are others issues i would like to point out. 
I have created a video to show some problems.
I hope it will be helpful. If i'm not clear in the video (or having some problems with site) feel free to ask me.
[](https://uloz.to/!bBb1HjdicU1Q/texture-lock-issues0001-1371-avi)

Keep on awesome work ;)

**Comment by nutti** [comment]
@NO4ME 

OK, thanks.

> Thank you for fixing issue in object mode but there are others issues i would like to point out.

Is this issue related to the issue we discussed in this page?
If the issue is different, I would appreciate to make new issue.

Thanks.

**Comment by NO4ME** [comment]
It is a different issue from this discussion. I'll put it to a new issue, so there won't be chaos.
Thank you

**Comment by nutti** [comment]
Cool, I will wait you.
Thanks
