### ISSUE TITLE
Stop/Start issue

### ISSUE THREAD

**Issue by NO4ME** [nutti/Magic-UV#90]
Thank you for fixing issue in object mode but there are others issues i would like to point out.
I have created a video to show some problems.
I hope it will be helpful. If i'm not clear in the video (or having some problems with site) feel free to ask me.

[video](https://uloz.to/!bBb1HjdicU1Q/texture-lock-issues0001-1371-avi)

Keep on awesome work ;)

**Comment by nutti** [comment]
Thanks.

Sorry, I have not finished to fix the issue you mentioned in video.
#89 only fixes the issue when the edit mode is terminated.

This issue is now fixing, so please wait.

**Comment by nutti** [comment]
Fixed this issue and already in develop branch.

https://github.com/nutti/Magic-UV/archive/develop.zip

**Comment by NO4ME** [comment]
Its awesome :D 

I can send you more important bugs ;)
