### ISSUE TITLE
[5.1.0] Copy / Paste between 1 or more object not working (unless they have UVmap)

### ISSUE THREAD

**Issue by schroef** [nutti/Magic-UV#93]
This seems to be an old bug or issue. I now this has been raised before. When a users want to copy /paste between a single or multiple meshes nothing happens unless to the target objects dont have an existing uvmap. I thing it would be nice if the option is there that its automatically added, as well as the name of the uv_texture is added as well. I think hardly any modeler does it, but naming items is key to a organised scene, so copy the name as well should be added.

I also think that if the object has an UVmap already one should be added and not destroying any existing one.

This is the error i got copy / pasting between object with and without UVmap
![screen shot 2018-06-02 at 3 39 29 am](https://user-images.githubusercontent.com/6923008/40872142-85c8fb76-6617-11e8-8450-23781f45ebc1.png)

**Comment by schroef** [comment]
AS extra option perhaps it can add the uv texture as well. That mean way less work assigning the same text to all other objects

**Comment by nutti** [comment]
>  I thing it would be nice if the option is there that its automatically added, as well as the name of the uv_texture is added as well.
> AS extra option perhaps it can add the uv texture as well.

Looks good.

> I also think that if the object has an UVmap already one should be added and not destroying any existing one.

I don't think so.
I'm using this feature to replace existed UVMap. It is boring to delete the newly created UVMap after pasting UV.

**Comment by schroef** [comment]
Why deleting it, perhaps there is a usage for it. Because current method will destroy it.

PS what happened to the earlier request for adding a map automatically,. Thought it was implemented already?

**Comment by nutti** [comment]
> PS what happened to the earlier request for adding a map automatically,. Thought it was implemented already?

Not yet in Copy/Paste feature. But I think it is good feature, and will add it.


> Why deleting it, perhaps there is a usage for it. Because current method will destroy it.

Your request is adding an UVMap everytime when I executed Paste UV, isn't it?
I would not like to add new UVMap after executing Paste UV.

**Comment by nutti** [comment]
Adding option to add new UVMap looks good.
But I think This option should be added to the one of the menu.
For example **[New UVMap]** .

**Comment by nutti** [comment]
Fixed it.
Can you check the below version?

https://github.com/nutti/Magic-UV/archive/issue_93.zip

**Comment by nutti** [comment]
It has already in develop branch. So I will close this issue.
Reopen or make new issue if there is a problem.
