### ISSUE TITLE
[5.1.0] Preserve UV - Error Float division by zero

### ISSUE THREAD

**Issue by schroef** [nutti/Magic-UV#94]
rv 5.1.0
BL 2.79b
osx 10.10.2

I tried using Preserve UV and when selecting either one face or multiple, i see this error about 'Float division by Zero"
![screen shot 2018-06-02 at 5 50 38 pm](https://user-images.githubusercontent.com/6923008/40881151-0c6f206c-668e-11e8-8a5f-c558649a1fe5.png)

**Comment by nutti** [comment]
Does the image which you tried to change, have a image whose size is more than 1?
I'm curious about this error is raised.

can you send me a situation or send me a .blend file?

**Comment by schroef** [comment]
What do you mean a size more than 1, more than 1 what? You mean 1x1 or 2x1 like that, so perhaps you mean UxV dimensions than?

I just tried a different model which already has 2 uvmaps, one has texture of 1x1 the other uv tex is about 1x2 orso. I could transfer the 1x2 uv to the 1x1 without a warning.

Ill see if i can the other model again and narrow the issue.

**Comment by schroef** [comment]
I think the prior model now works. I had done the uv mapping already and check it. What i dont get is when i click preserve UV the, the uv texture changes automatically in the uv editor to some random other texture???

EDIT
its doesnt seem random after better checking, it takes the first file in alphabetically order in the textures list.

Also what is the use for the Preserve UV dropdown, i can choose an alignment i guess. But changed and redoing it doesnt do anything. After redoing it a couple times, sometimes i see it jump a bit on the new texture.

Also when i redo this step and pick the original text which has something like 1x3 orso. The ratio is proper anymore. Ill make a test model for you using simple uv textures.

**Comment by schroef** [comment]
Well i was trying to make you a test model and i see this popup showing again. I was making simple uv textures with the same ratio the original plant part had. 

First i thought this error came because the file only has 1 texture when i was setting it up. Because the Presurve UV action move the UVs to the first iamge texture in the list, which is weird.

EDIT
i think i found my issue, the render result image, if this is blank than the errors show. When i delete this render result image. The popup doesnt show. I think the there is something wrong with automatically picking the first image, i dont understand why that step is done?

Here's the model
[Preserve UV-test-model.blend.zip](https://github.com/nutti/Magic-UV/files/2076954/Preserve.UV-test-model.blend.zip)

**Comment by schroef** [comment]
I found my issue, i always use the hot U, so i dont look at the toolbar menu. I see i need to use the dropdown from there. That was causing my weird behavior.

Though the error when 1 image is empty still shows.

Also the first in the drop is None, which raises an error. But that is probably necessary because the enum cant be empty.

**Comment by nutti** [comment]
Thanks.

I understand completely your issue. It is a problem which I missed to add the sub menu to Preserve UV Aspect.

Now, I fixed this problem and you can try it from develop branch.

**Comment by schroef** [comment]
Doesn't this also mean other settings should be look at, see which ones need a sub menu in the hotkeys?

**Comment by nutti** [comment]
I checked quickly, but no need to add sub menu.
But if you have a suggestion, feel free to tell me.

**Comment by schroef** [comment]
Well perhaps a dialog window than. The shortcuts are they to make the workflow fast. Now using this options still neess the user to use the tools panel which makes the shortcut kindoff useless I think
