### ISSUE TITLE
Copy/Paste all UVMaps

### ISSUE THREAD

**Issue by NO4ME** [nutti/Magic-UV#96]
Hi, this is just my suggestion but I think it would be useful to copy all UVMaps in one go.

![maps_all](https://user-images.githubusercontent.com/39378030/41417998-1b242c5a-6fef-11e8-8ab6-a58ded852c3d.jpg)

Cheers

**Comment by nutti** [comment]
Can you show me the behavior about the paste?
All UV maps are pasted to **ONE** UV map?

**Comment by NO4ME** [comment]
Two objects have the same number of UVMaps with same names. **All** should copy individual UVMaps from one object to another.

![copypasteall](https://user-images.githubusercontent.com/39378030/41520673-212fe53e-72cf-11e8-9632-823e5b27dd87.jpg)

**Comment by nutti** [comment]
Thanks. I got it.

**Comment by nutti** [comment]
Your request is already in develop branch.

https://github.com/nutti/Magic-UV/archive/develop.zip

Thanks for a great feedback.
