### ISSUE TITLE
Update for Blender 2.8

### ISSUE THREAD

**Issue by nutti** [nutti/Magic-UV#97]
Update this add-on for Blender 2.8.
Also, the backward compatibility is need to be remained.

Any report about the problem raised in 2.8, are welcome.

TODO list for features to support for Blender 2.8.

- [x] Copy/Pate UV
- [x] Transfer UV
- [x] Flip/Rotate UV
- [x] Mirror UV
- [x] Move UV
- [x] World Scale UV
- [x] Preserve UV Aspect
- [x] Texture Lock
- [x] Texture Wrap
- [x] UV Sculpt
- [x] Unwrap Constraint
- [x] Texture Projection
- [x] UVW
- [x] Align UV
- [x] Smooth UV
- [x] Select UV
- [x] Pack UV (Extension)
- [x] Align UV Cursor
- [x] UV Cursor Location
- [x] UV Bounding Box
- [x] UV Inspection

**Comment by nutti** [comment]
There is a break change in bgl module.
The feature using bgl module will be broken in 2.8.

* UV Sculpt
* Texture Projection
* UV Bounding Box
* UV Inspection

I think the new API will be released soon and I try to fix these features after that.

**Comment by schroef** [comment]
Is there info about why they break or is that the info your waiting on?

I also have a couple addons i need to check :(

**Comment by nutti** [comment]
@schroef 

Below page shows the breakage about ```bgl``` module.
https://en.blender.org/index.php/Dev:2.8/Source/OpenGL

Most of functions are deleted from Blender 2.8.
So, most of add-on that uses ```bgl``` module will not do work.

And there will be an announcement to all add-on developer about API changes after Blender 2.8 beta version is released.
I will wait this announce.

https://www.pcper.com/news/General-Tech/Blender-28-Expected-Release-Schedule-Published

**Comment by nutti** [comment]
Before updating to Blender 2.8, I will release Magic UV v5.2.
I think this is a final release before Blender 2.8.

The milestone to Magic UV v5.2 is as follows.

https://github.com/nutti/Magic-UV/milestone/12

**Comment by schroef** [comment]
Sorry for the late reply, but this kind of sucks. Im editting a different addon which use bgl to render images to the viewport from a different render engine.

That means i cant use live ir render preview no more. I think i need todo some reading about this subject it would be a shame if that isn possible at all any more.

**Comment by nutti** [comment]
@schroef 

I think you should try the newest version of Blender 2.8 from Blender official site.
There are lots of missing API on it.

**Comment by nutti** [comment]
@schroef 

> But on the other hand they also state add-on device should NOT be updating their add-ons yet. It's still alpha and a lot of things can change.

Yes, I think so.
I'll wait after the Python API is fixed.

**Comment by nutti** [comment]
New API for Blender 2.8 is revealed.

https://wiki.blender.org/wiki/Reference/Release_Notes/2.80/Python_API/Addons

I will tackle to change my scripts for Blender 2.8.

**Comment by nutti** [comment]
At first, I revise the script to enable Copy/Paste UV for Blender 2.8 and move legacy code to the lagacy directory.


- [ ] Copy/Pate UV
- [ ] Transfer UV
- [ ] Flip/Rotate UV
- [ ] Mirror UV
- [ ] World Scale UV
- [ ] Preserve UV Aspect
- [ ] Texture Lock
- [ ] Texture Wrap
- [ ] UV Sculpt
- [ ] Unwrap Constraint
- [ ] Texture Projection
- [ ] UVW
- [ ] Align UV
- [ ] Smooth UV
- [ ] Select UV
- [ ] Pack UV (Extension)
- [ ] Align UV Cursor
- [ ] UV Cursor Location
- [ ] UV Bounding Box
- [ ] UV Inspection

**Comment by nutti** [comment]
All features are supported on Blender 2.8 as well as 2.79.
