### ISSUE TITLE
Question: Blender Artists thread was missing

### ISSUE THREAD

**Issue by nutti** [nutti/Magic-UV#98]
I recently logged in Blender Artists after BA v2.0 release.
I also noticed that Blender Artists thread about Magic UV is missing.

I'm now contacting to the administrator about this problem.
Is there any clue why this problem is happened?

**Comment by schroef** [comment]
I noticed that too, it was there last week or the week before.

**Comment by nutti** [comment]
@schroef 

Thanks.
I have not logged in Blender Artist for last 2 or 3 months, so I did not get why Magic UV thread is missed.
I confirmed that other threads I made are existed.

**Comment by schroef** [comment]
Have you contacted the blender admin about this already? When i do a search for the addon after a lot of scrolling i still gavent seen it as well. I do remember seeing some post about missing threads.

**Comment by schroef** [comment]
Ow just found your post about that missing thread. I do see each link has a different header url. Did you make new threads with each new update?

**Comment by nutti** [comment]
No, I have not made new thread since I made a first Magic UV thread.

**Comment by nutti** [comment]
There is no response from the administrator.
Should I tell him directly?

**Comment by nutti** [comment]
@schroef 

I sent a direct message, but he does not reply it yet.
I think we should post new thread. What do you think?

**Comment by nutti** [comment]
I created new topic about Magic UV.  
Maybe the old BA topic was discarded.

https://blenderartists.org/t/magic-uv/1134694
